"""Stable contracts for trusted Open Agent World Python plugins."""
from backend.execution_config import ComputeTarget, EnvironmentProfile, SecretRequirement
from backend.resources.artifact_models import ArtifactPublish, ArtifactMaterialize

from backend.plugins.builtin import AgentNodeBehavior, AgentNodeTemplateHandler
from backend.plugins.registry import PluginAsset, PackDefinition

from backend.plugins.summoning import NodeSummoningDefinition, SummoningAction, SummoningPolicy
from backend.plugins.documents import NodeDocumentAction, NodeDocumentDefinition, NodeDocumentDownload
from backend.plugins.documents import NodeDocumentTransformation
from backend.plugins.containers import NodeContainerDefinition
from backend.plugins.execution import ExecutionPolicy, NodeExecutionDefinition, WorkItem, WorkOutcome

from backend.agents import (
    AgentCapabilityProvider,
    AgentConfig,
    AgentConfigurationError,
    AgentDependencyError,
    AgentEvent,
    AgentEventType,
    AgentInfo,
    AgentNotFoundError,
    AgentRuntimeError,
    AgentStateError,
    AgentStatus,
    RuntimeProvider,
    ScopedToolDefinition,
    ToolParameter,
)
from backend.capabilities import Capability
from backend.errors import (
    ConflictError,
    GraphValidationError,
    NotFoundError,
    PermissionDeniedError,
    PluginCompatibilityError,
    PluginUnavailableError,
    ResourceValidationError,
    RevisionConflictError,
    RuntimeUnavailableError,
)
from backend.plugins import (
    PLUGIN_API_VERSION,
    CapabilityContext,
    CapabilityGrantDefinition,
    CapabilityDefinition,
    CapabilitySelector,
    AgentNodeLifecycle,
    ConversationNodeLifecycle,
    ManagedResourceLifecycle,
    ManagedResourceRemoval,
    NodeLifecycleContext,
    NodeLifecycleHandler,
    NodeLifecycleNodes,
    NodeLifecycleTransaction,
    NodeTemplateBinary,
    NodeTemplateCaptureContext,
    NodeTemplateCaptureResources,
    NodeTemplateDependency,
    NodeTemplateDependencyKind,
    NodeTemplateHandler,
    NodeTemplateRestoreContext,
    NodeTemplateRestoreResources,
    NodeTypeDefinition,
    Plugin,
    PluginDescriptor,
    PluginDefinition,
    PluginRegistration,
    PluginRegistry,
    RelationshipDefinition,
    RuntimeProviderFactory,
    SandboxNodeLifecycle,
)
from backend.state import MergePolicy, StateFieldDefinition, StateSchema
from backend.runs import InvocationContext, RuntimeInput
from backend.world.models import Card, CardCreate, CardPatch, Edge

__all__ = [
    "PackDefinition",
    "NodeDocumentTransformation",
    "ArtifactPublish",
    "ArtifactMaterialize",
    "ComputeTarget", "EnvironmentProfile", "SecretRequirement",
    "PluginAsset",
    "AgentNodeBehavior", "AgentNodeTemplateHandler",
    "NodeSummoningDefinition", "SummoningAction", "SummoningPolicy",
    "ExecutionPolicy",
    "NodeExecutionDefinition",
    "WorkItem",
    "WorkOutcome",
    "PLUGIN_API_VERSION",
    "NodeDocumentAction",
    "NodeDocumentDefinition",
    "NodeDocumentDownload",
    "NodeContainerDefinition",
    "AgentCapabilityProvider",
    "AgentConfig",
    "AgentConfigurationError",
    "AgentDependencyError",
    "AgentNodeLifecycle",
    "AgentEvent",
    "AgentEventType",
    "AgentInfo",
    "AgentNotFoundError",
    "AgentRuntimeError",
    "AgentStateError",
    "AgentStatus",
    "Capability",
    "CapabilityContext",
    "CapabilityGrantDefinition",
    "CapabilityDefinition",
    "CapabilitySelector",
    "Card",
    "CardCreate",
    "CardPatch",
    "ConflictError",
    "ConversationNodeLifecycle",
    "Edge",
    "GraphValidationError",
    "InvocationContext",
    "MergePolicy",
    "ManagedResourceLifecycle",
    "ManagedResourceRemoval",
    "NodeLifecycleContext",
    "NodeLifecycleHandler",
    "NodeLifecycleNodes",
    "NodeLifecycleTransaction",
    "NodeTemplateBinary",
    "NodeTemplateCaptureContext",
    "NodeTemplateCaptureResources",
    "NodeTemplateDependency",
    "NodeTemplateDependencyKind",
    "NodeTemplateHandler",
    "NodeTemplateRestoreContext",
    "NodeTemplateRestoreResources",
    "NodeTypeDefinition",
    "NotFoundError",
    "PermissionDeniedError",
    "Plugin",
    "PluginCompatibilityError",
    "PluginDescriptor",
    "PluginDefinition",
    "PluginRegistration",
    "PluginRegistry",
    "PluginUnavailableError",
    "RelationshipDefinition",
    "ResourceValidationError",
    "RevisionConflictError",
    "RuntimeProvider",
    "RuntimeProviderFactory",
    "RuntimeInput",
    "RuntimeUnavailableError",
    "SandboxNodeLifecycle",
    "ScopedToolDefinition",
    "StateFieldDefinition",
    "StateSchema",
    "ToolParameter",
]
