from __future__ import annotations

from typing import Any, Protocol
from backend.plugins.state import CardStateStore


class CapabilityContext(Protocol):
    """Narrow host operations available to trusted capability handlers."""

    @property
    def state(self) -> CardStateStore | None: ...

    async def node_resource_action(self, capability: Any, action: str, arguments: dict[str, Any]) -> dict[str, Any]: ...

    async def minister_action(self, capability: Any, arguments: dict[str, Any]) -> Any: ...

    async def read_file_preview(self, capability: Any, arguments: dict[str, Any]) -> Any: ...
    async def collection_members(self, capability: Any) -> dict[str, Any]: ...

    # API 1.26: the calling Agent's own live capability of ``kind`` on ``target_id``,
    # for example to check a cited source it claims to have read. Raises
    # PermissionDeniedError when the Agent does not currently hold it; a missing
    # target reports the same way, so the answer never reveals unconnected nodes.
    async def agent_capability(self, capability: Any, kind: str, target_id: str) -> Any: ...

    async def artifact_action(self, capability: Any, arguments: dict[str, Any]) -> Any: ...

    async def send_conversation_message(self, capability: Any, arguments: dict[str, Any]) -> Any: ...

    async def legion_state_action(self, capability: Any, arguments: dict[str, Any]) -> dict[str, Any]: ...

    async def summoning_action(self, capability: Any, arguments: dict[str, Any]) -> dict[str, Any]: ...

    async def node_document_action(self, capability: Any, action: str, arguments: dict[str, Any], expected_revision: int | None = None) -> dict[str, Any]: ...

    async def node_execution_action(self, capability: Any, action: str, arguments: dict[str, Any]) -> dict[str, Any]: ...

    async def node_delegation_action(self, capability: Any, action: str, arguments: dict[str, Any]) -> dict[str, Any]: ...

    async def communicate(
        self, source_agent_id: str, target_agent_id: str, message: str
    ) -> Any: ...

    async def request_conversation_turn(
        self,
        source_agent_id: str,
        conversation_id: str,
        participant_agent_id: str,
        message: str,
    ) -> Any: ...

    def read_text(self, agent_id: str, resource_id: str) -> dict[str, Any]: ...

    async def replace_text(
        self, agent_id: str, resource_id: str, content: str
    ) -> dict[str, Any]: ...

    def view_image(self, agent_id: str, resource_id: str) -> Any: ...

    async def execute_sandbox(
        self, agent_id: str, sandbox_id: str, argv: list[str], *, environment_id: str | None = None, target_id: str | None = None, timeout_seconds: float | None = None, wait_seconds: float | None = None
    ) -> dict[str, Any]: ...

    async def cancel_sandbox_command(self, agent_id: str, sandbox_id: str, command_id: str) -> dict[str, Any]: ...

    async def start_sandbox(self, agent_id: str, sandbox_id: str) -> dict[str, Any]: ...

    async def stop_sandbox(self, agent_id: str, sandbox_id: str) -> dict[str, Any]: ...

    async def inspect_sandbox(self, agent_id: str, sandbox_id: str) -> dict[str, Any]: ...

    async def install_python_packages(self, agent_id: str, sandbox_id: str, requirements: list[str], wait_seconds: float | None = None) -> dict[str, Any]: ...

    async def wait_sandbox_operation(self, agent_id: str, sandbox_id: str, operation_id: str | None = None, wait_seconds: float = 30) -> dict[str, Any]: ...

    async def copy_skill_resource(self, agent_id: str, sandbox_id: str, arguments: dict[str, Any]) -> dict[str, Any]: ...

    async def run_skill_script(
        self, agent_id: str, sandbox_id: str, arguments: dict[str, Any]
    ) -> dict[str, Any]: ...
