// @vitest-environment jsdom
import { useState } from 'react';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import { FaceDesignerCanvas } from './FaceDesignerCanvas';
import { faceStudio } from './faceDesign';
import type { FaceDesign, FunctionDesign, SurfaceDesign } from './types';

afterEach(cleanup);
const initial: FaceDesign = { title: '每日灵感', description: '收集好想法', variant: 'icon', tone: 'sand', color: '#617b66', icon: 'sparkles', finish: 'normal', layout: 'stack', help_text: '', button_label: '开始' };
const functionDesign: FunctionDesign = { fields: [{ key: 'message', label: '测试输入', type: 'text', default: '默认文字', required: false }], operation: 'template', template: '', separator: '' };
function Editor({ broken = false }) {
  const [face, setFace] = useState(() => {
    const studio = faceStudio(initial);
    if (broken) studio.modes.preview!.design!.tokens = { text: '#eee5d6' };
    return { ...initial, studio };
  });
  return <><FaceDesignerCanvas face={face} functionDesign={functionDesign} onChange={patch => setFace(current => ({ ...current, ...patch }))} /><output data-testid="draft">{JSON.stringify(face)}</output></>;
}
const draft = (): FaceDesign => JSON.parse(screen.getByTestId('draft').textContent!);
const surface = () => draft().studio!.modes.preview!;
const geometry = (value: SurfaceDesign) => value.elements.map(({ id, x, y, width, height, font_size, align }) => ({ id, x, y, width, height, font_size, align }));
const step = (name: string) => fireEvent.click(within(screen.getByRole('navigation', { name: '设计步骤' })).getByRole('button', { name: name === '工艺层' ? '选择油墨第 1 层' : name }));
const openPanel = (name: string) => { const summary = screen.getByText(name, { selector: 'summary span' }); summary.closest('details')!.open = true; };
const addProcess = (name: string) => { screen.getByLabelText('添加工艺层', { selector: 'summary' }).closest('details')!.open = true; fireEvent.click(screen.getByRole('button', { name })); };
const preset = (name: string) => { fireEvent.click(screen.getByRole('button', { name: '预设' })); fireEvent.click(screen.getByRole('button', { name })); step('工艺层'); };
describe('progressive designer workflow', () => {
  it('adds multiple authored buttons, edits their behavior and shows non-blocking proof warnings', () => {
    render(<Editor />);
    step('成品');
    expect(screen.getByRole('status', { name: '卡面按钮提醒' }).textContent).toContain('仍可保存和印刷');
    step('工艺层'); openPanel('按钮');
    const before = geometry(surface());
    fireEvent.click(screen.getByRole('button', { name: '添加展开按钮' }));
    const id = surface().elements.at(-1)!.id;
    expect(surface().elements.at(-1)).toMatchObject({ kind: 'button', button: { action: 'open' }, placement: 'free' });
    fireEvent.change(screen.getByRole('textbox', { name: '按钮' }), { target: { value: '查看详情' } });
    fireEvent.change(screen.getByLabelText('按钮底色'), { target: { value: '#aabbcc' } });
    fireEvent.change(screen.getByLabelText('按钮功能'), { target: { value: 'custom' } });
    expect(surface().elements.at(-1)).toMatchObject({ id, text: '查看详情', button: { action: 'custom', background: '#aabbcc' } });
    fireEvent.click(screen.getByRole('button', { name: '添加展开按钮' }));
    expect(surface().elements.filter(item => item.kind === 'button')).toHaveLength(2);
    expect(geometry(surface()).slice(0, before.length)).toEqual(before);
    fireEvent.click(screen.getByRole('button', { name: '撤销' }));
    expect(surface().elements.filter(item => item.kind === 'button')).toHaveLength(1);
    expect(surface().elements.at(-1)!.id).toBe(id);
    step('成品');
    expect(screen.getByRole('status', { name: '卡面按钮提醒' }).textContent).toContain('逻辑挂载尚未启用');
  });
  it('starts with paper and moves through paper, individual process passes and the finished proof', () => {
    const { container } = render(<Editor />);
    const rail = screen.getByRole('navigation', { name: '设计步骤' });
    expect(within(rail).getAllByRole('button').filter(button => !button.closest('.process-add-menu')).map(button => button.getAttribute('aria-label'))).toEqual(['卡纸', '选择油墨第 1 层', '成品']);
    expect(within(rail).getByRole('button', { name: '卡纸' }).getAttribute('aria-current')).toBe('step');
    expect(screen.getByRole('group', { name: '卡纸材质' })).toBeTruthy();
    expect(screen.queryByRole('spinbutton')).toBeNull();
    expect(container.querySelector('.face-properties')).toBeNull();
    expect(within(screen.getByRole('group', { name: '卡片模式设计画布' })).queryByText(initial.title)).toBeNull();
    fireEvent.click(screen.getByRole('button', { name: '下一步' }));
    expect(screen.getByRole('region', { name: '当前工艺层' })).toBeTruthy();
    expect(screen.getByRole('button', { name: '设计标题' })).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: '下一步' }));
    expect(screen.getByRole('combobox', { name: '查看印刷层' })).toBeTruthy();
    fireEvent.keyDown(rail, { key: 'ArrowLeft' });
    expect(screen.queryByLabelText('覆盖范围')).toBeNull();
    fireEvent.keyDown(rail, { key: 'ArrowRight' });
    expect(screen.getByRole('combobox', { name: '查看印刷层' })).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: '上一步' }));
    expect(within(rail).getByRole('button', { name: '选择油墨第 1 层' }).getAttribute('aria-current')).toBe('step');
  });
  it('adds and removes editable layers without moving siblings and supports exact undo and redo', () => {
    render(<Editor />);
    preset('应用 Badge 版式');
    expect(surface().design!.recipe).toBe('badge');
    fireEvent.focus(screen.getByRole('button', { name: '设计标题' }));
    const positions = geometry(surface());
    fireEvent.change(screen.getByRole('textbox', { name: '标题' }), { target: { value: '新的灵感卡，标题变长也保持排版' } });
    expect(geometry(surface())).toEqual(positions);
    fireEvent.click(screen.getByRole('button', { name: '选择油墨第 1 层' }));
    const before = draft();
    openPanel('文本'); fireEvent.click(screen.getByRole('button', { name: '副标题' }));
    expect(surface().elements.find(element => element.kind === 'subtitle')?.placement).toBe('free');
    expect(geometry(surface()).slice(0, positions.length)).toEqual(positions);
    const added = draft();
    fireEvent.click(screen.getByRole('button', { name: '撤销' }));
    expect(draft()).toEqual(before);
    fireEvent.click(screen.getByRole('button', { name: '重做' }));
    expect(draft()).toEqual(added);
    fireEvent.focus(screen.getByRole('button', { name: '设计副标题' }));
    fireEvent.click(screen.getByRole('button', { name: '删除此内容' }));
    expect(surface().elements).toEqual(before.studio!.modes.preview!.elements);
    fireEvent.click(screen.getByRole('button', { name: '撤销' }));
    expect(draft()).toEqual(added);
  });
  it('unlocks individual or all layers in place and preserves geometry across ink and material edits', () => {
    render(<Editor />);
    preset('应用 Compact 版式');
    const original = surface();
    fireEvent.focus(screen.getByRole('button', { name: '设计标题' }));
    fireEvent.click(screen.getByRole('button', { name: '转为自由图层' }));
    expect(surface().elements).toEqual(original.elements.map(element => element.kind === 'title' ? { ...element, placement: 'free' } : element));
    preset('全部自由编辑'); fireEvent.focus(screen.getByRole('button', { name: '设计标题' }));
    expect(surface().elements).toEqual(original.elements.map(element => ({ ...element, placement: 'free' })));
    const before = geometry(surface());
    fireEvent.change(screen.getByRole('textbox', { name: '标题' }), { target: { value: '重新编写的一段很长的标题，也不应挤压或变形' } });
    fireEvent.change(screen.getByRole('slider', { name: '油墨浓度' }), { target: { value: '42' } });
    expect(screen.queryByRole('group', { name: '叠印方式' })).toBeNull();
    expect(surface().elements.find(element => element.kind === 'title')!.print).toEqual({ opacity: .42, blend: 'normal' });
    const titlePrint = within(screen.getByRole('group', { name: '卡片模式设计画布' })).getByText(draft().title).parentElement!;
    expect(titlePrint.style.opacity).toBe('0.42');
    expect(titlePrint.style.mixBlendMode).toBe('normal');
    step('卡纸');
    fireEvent.change(screen.getByLabelText('纸面颜色'), { target: { value: '#233332' } });
    step('工艺层');
    fireEvent.click(screen.getByRole('button', { name: '添加烫金' }));
    step('工艺层');
    addProcess('添加覆膜');
    fireEvent.change(screen.getByRole('combobox', { name: '覆膜类型' }), { target: { value: 'starlight' } });
    step('成品');
    expect(geometry(surface())).toEqual(before);
    expect(surface().design!.production).toMatchObject({ stock: { color: '#233332' }, layers: [{ kind: 'ink' }, { kind: 'foil' }, { kind: 'laminate', film: 'starlight' }] });
    step('工艺层');
    fireEvent.focus(screen.getByRole('button', { name: '设计标题' }));
    const x = screen.getByRole('spinbutton', { name: '位置 X' });
    fireEvent.change(x, { target: { value: '37' } }); fireEvent.blur(x);
    expect(surface().elements.find(element => element.kind === 'title')!.x).toBe(37);
    preset('应用 Split 版式');
    expect(surface().elements.find(element => element.kind === 'title')!.x).toBe(37);
    expect(geometry(surface()).filter(element => element.id !== 'title')).toEqual(before.filter(element => element.id !== 'title'));
  });
  it('records a polish correction as one reversible edit and preserves material settings', () => {
    render(<Editor broken />);
    const before = draft();
    fireEvent.click(screen.getByRole('button', { name: '润色' }));
    expect(surface().design!.tokens.text).not.toBe('#eee5d6');
    fireEvent.click(screen.getByRole('button', { name: '撤销' }));
    expect(draft()).toEqual(before);
    step('工艺层');
    addProcess('添加覆膜');
    fireEvent.change(screen.getByRole('combobox', { name: '覆膜类型' }), { target: { value: 'starlight' } });
    expect(surface().design!.production!.layers!.at(-1)?.film).toBe('starlight');
    fireEvent.click(screen.getByRole('button', { name: '预览' }));
    expect(screen.getByRole('navigation', { name: '设计步骤' })).toBeTruthy();
  });
  it('keeps normal style choices consistent across views while advanced overrides stay local', () => {
    render(<Editor />);
    preset('应用 Compact 版式');
    openPanel('图像');
    fireEvent.click(screen.getByRole('button', { name: '几何网格' }));
    step('工艺层');
    addProcess('添加覆膜');
    fireEvent.change(screen.getByRole('combobox', { name: '覆膜类型' }), { target: { value: 'starlight' } });
    for (const mode of ['node', 'preview', 'inspector', 'workspace'] as const) {
      expect(draft().studio!.modes[mode]!.design).toMatchObject({ recipe: 'compact', production: { layers: [{ kind: 'ink', pattern: { motif: 'grid' } }, { kind: 'laminate', film: 'starlight' }] } });
    }
    const before = draft();
    fireEvent.click(screen.getByRole('button', { name: '高级设置' }));
    fireEvent.click(screen.getByRole('button', { name: '样式令牌' }));
    fireEvent.change(screen.getByLabelText('主要文字'), {target: {value: '#354139'}});
    expect(surface().design!.tokens.text).toBe('#354139');
    expect(draft().studio!.modes.workspace).toEqual(before.studio!.modes.workspace);
  });
  it('nudges only the selected layer and ignores editing keys from a card input', () => {
    render(<Editor />);
    step('工艺层');
    fireEvent.change(screen.getByRole('combobox', { name: '预览显示模式' }), { target: { value: 'workspace' } });
    fireEvent.focus(screen.getByRole('button', { name: '设计标题' }));
    const before = draft().studio!.modes.workspace!;
    const stage = screen.getByRole('group', { name: '工作区模式设计画布' });
    fireEvent.keyDown(stage, { key: 'ArrowRight' });
    const nudged = draft().studio!.modes.workspace!;
    expect(nudged.elements.find(element => element.kind === 'title')!.x).toBe(before.elements.find(element => element.kind === 'title')!.x + 1);
    expect(nudged.elements.filter(element => element.kind !== 'title')).toEqual(before.elements.filter(element => element.kind !== 'title'));
    const field = within(stage).getByRole('textbox', { name: '测试输入' });
    fireEvent.keyDown(field, { key: 'ArrowRight' });
    fireEvent.keyDown(field, { key: 'Backspace' });
    fireEvent.keyDown(field, { key: 'Delete' });
    expect(draft().studio!.modes.workspace).toEqual(nudged);
  });
});
