import { useLocale } from "@oaw/plugin-api";

const copy = {
  index: ["Research hub", "研究中枢"], trail: ["Exploration route", "探索路径"], paper: ["Paper", "文献"], method: ["Method", "方法"],
  web: ["Web source", "网页来源"], perspective: ["Perspective", "共同视角"], collection: ["Core bibliography", "核心文献集"], all: ["All", "全部"],
  subtitle: ["Keep the index at basecamp. Papers and findings grow along routes outside it.", "大本营维护目录，文献与发现沿营地外的路径展开。"],
  sync: ["Arrange exploration map", "整理探索地图"], syncHelp: ["Create the index and route cards; move scoped Papers outside basecamp. Existing Papers and reading notes are preserved.", "建立目录和路标，将范围内的文献展开到营地外；保留原 Paper 与阅读记录。"],
  saving: ["Saving…", "正在保存…"], refresh: ["Refresh", "刷新"], search: ["Search the bibliography and findings", "搜索目录与发现"],
  scope: ["Research scope", "研究范围"], openIndex: ["Open research hub", "打开研究中枢"], open: ["Open", "打开"], details: ["Details", "详情"],
  empty: ["No entries yet. Arrange the map after adding Papers or routes.", "暂无条目。添加文献或路标后，可整理探索地图。"],
  unknown: ["This entry is no longer present in the current scope.", "当前范围中已不存在此条目。"], noScope: ["This card needs a research scope. Create it from the scope's exploration map.", "此卡片尚未关联研究范围，请从研究范围的探索地图中创建。"],
  loading: ["Loading index…", "正在读取目录…"], current: ["Current scope", "当前范围"], historical: ["Historical scope", "历史范围"],
  add: ["Add a finding", "添加沿途发现"], link: ["Connect branches", "连接探索分支"], core: ["Select core Papers", "选定核心文献"], camp: ["Attach a search camp", "挂载检索营地"],
  cancel: ["Cancel", "取消"], save: ["Save", "保存"], type: ["Finding type", "发现类型"], title: ["Title", "标题"], url: ["Source URL", "来源网址"],
  rationale: ["Selection or connection rationale", "选择或连接理由"], sources: ["Source Papers", "来源文献"], branch: ["Exploration branch", "探索分支"],
  anyBranch: ["Scope-wide", "整个研究范围"], selectBranch: ["Choose a branch", "选择探索分支"], source: ["From", "起点"], target: ["To", "终点"],
  relation: ["Relationship", "关系"], related: ["Related perspective", "相关视角"], supports: ["Supports", "支持"], contrasts: ["Contrasts", "对照 / 冲突"],
  contains: ["Contains", "收录"], discovers: ["Discovers", "发现"], methodRelation: ["Uses method", "关联方法"],
  linkHelp: ["Connect existing findings with a stated rationale. Shared perspectives remain one node across branches; a link is not scientific verification.", "用明确理由连接已有发现。不同分支共享同一个视角节点；连线不等于科学核验。"],
  coreHelp: ["Select Papers and record why they form this branch's core bibliography. This is a curated selection, not an automatic quality ranking.", "选择论文并说明它们为何构成本分支的核心目录。核心集是有理由的选编，不是自动质量排名。"],
  campHelp: ["Attach an existing Barracks to this route. It uses the existing delegation workflow and permissions; attachment does not launch workers.", "将已有兵营挂载到这条路径，复用任务委派与现有权限；挂载不会自动启动工作者。"],
  barracks: ["Existing Barracks", "已有兵营"], noBarracks: ["No Barracks available. Add one to basecamp first.", "暂无可用兵营，请先在大本营添加兵营。"],
  viewCamp: ["Open camp", "打开营地"], routes: ["Connected routes and findings", "关联路径与发现"], members: ["Included Papers", "收录文献"],
  methodDetail: ["Source-bound method", "有来源的方法"], purpose: ["Purpose", "用途"], steps: ["Steps", "方法步骤"], missing: ["Still missing", "待补信息"],
  sourceText: ["Read the source", "回到原文精读"], export: ["Export method Skill", "导出方法 Skill"], assimilate: ["Add to method library", "加入方法知识库"],
  assimilated: ["Imported to the method library from the source snapshot.", "已按来源快照导入方法知识库。"],
  micro: ["Micro strategy · close reading", "微观策略 · 论文精读"], meso: ["Meso strategy · field snapshot", "介观策略 · 领域快照"],
  more: ["Open workspace", "打开工作区"], scopeDetails: ["Open scope and method records", "打开研究范围与方法记录"],
  sourceHelp: ["Record source Papers or an HTTPS web source. A perspective is a attributed research lead, not an established conclusion.", "记录来源论文或 HTTPS 网页。共同视角保留出处，作为研究线索而非既定结论。"],
  safeUrl: ["Use a public HTTPS source URL.", "请填写公开来源的 HTTPS 网址。"], noResults: ["No matching entries.", "没有匹配条目。"],
  attach: ["Attach camp", "挂载营地"], recordedCamps: ["Route camps", "路径营地"], selection: ["Selected", "已选"],
  stageMicro: ["Queue close-reading task", "加入精读任务"], stageBranch: ["Queue route-search task", "加入路径检索任务"],
  stageMethod: ["Queue method study", "加入方法精读任务"], tasks: ["Research task board", "研究任务看板"],
  taskGoal: ["Reading goal and acceptance criteria", "精读目标与验收要求"], searchGoal: ["Search goal and evidence gap", "检索目标与证据缺口"],
  taskHelp: ["Save a pending plan with source references and the current scope budget. The coordinator schedules it using existing Skills and permissions.", "保存含来源定位与当前范围预算的待执行计划，由协调 Agent 使用已有技能和权限安排。"],
  taskBoardMissing: ["Link a research task board in this scope before staging work.", "请先为此研究范围关联任务看板。"],
  staged: ["Task added to the existing task board; it has not been started.", "已加入现有任务看板，尚未启动。"],
  roadMap: ["Exploration roads", "探索道路"], station: ["Departure station", "始发站"], trunk: ["Main road", "主干道路"],
  roadHelp: ["Unsorted Papers stay on the main road. Signposts lead to branches; organize navigation without changing source evidence.", "未分类文献先沿主干道路排列，路标引向支路；整理导航不会改变文献来源与证据。"],
  roadEmpty: ["No road has been organized yet.", "尚未整理道路。"], roadInitialize: ["Organize roads", "建立道路目录"],
  roadInitializeHelp: ["Uses existing search provenance and preserves current card positions.", "按已有检索来源整理归属，保留当前卡片位置。"],
  roadLayout: ["Rearrange all roads", "重新排列道路"], roadLayoutOne: ["Arrange this road", "排列这条道路"],
  roadLayoutHelp: ["Move existing cards into ordered roadside positions.", "将现有卡片重新排到道路沿线。"],
  roadChain: ["Continue straight", "递进路标"], roadBranch: ["Branch off", "分叉路标"], roadSignpost: ["Signpost", "路标"],
  roadNewSignpost: ["Add a signpost", "新增路标"], roadSettings: ["Organize this road", "组织这条道路"], roadMove: ["Move to road", "挂载到道路"],
  roadParent: ["Parent road", "接入道路"], roadAnchor: ["Attach at", "接入位置"], roadTail: ["End of parent road", "道路末端"],
  roadSaveParent: ["Save connection", "保存接入位置"], roadMoveUp: ["Move earlier", "向前排列"], roadMoveDown: ["Move later", "向后排列"],
  roadFindings: ["Roadside findings", "沿途发现"], roadNoMembers: ["No findings on this road yet.", "这条道路尚无发现。"], roadUnknown: ["Source record unavailable", "来源记录暂不可用"],
  roadOpenFinding: ["Open finding", "打开发现"], roadAt: ["At", "接入于"], roadCount: ["Stops", "沿途站点"],
  roadModeHelp: ["Straight signposts continue a route; branch signposts split from it.", "递进路标延续路径，分叉路标从路径旁分出支路。"],
  roadMoveHelp: ["Navigation placement only; original search and source records remain attached.", "只调整道路挂载，保留原始检索与来源记录。"],
  roadBeside: ["Beside its source · off the main road", "在来源旁 · 未挂入道路"],
} satisfies Record<string, readonly [string, string]>;

export type ExplorationCopyKey = keyof typeof copy;
export function explorationText(key: ExplorationCopyKey) { return copy[key][useLocale.getState().locale === "zh-CN" ? 1 : 0]; }
