"""Constrained XRD pre-solver which preserves the CIF space group.

The solver is deliberately a pre-refinement step, rather than a replacement
for a Rietveld refinement.  It fits a small set of strong, resolved peaks to
give WPEM a better starting cell and set of asymmetric-unit coordinates.
"""

from __future__ import annotations

import copy
import json
import shutil
import warnings
from io import StringIO
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.optimize import least_squares
from scipy.signal import find_peaks

from ..Extinction.CifReader import CifFile


CELL_KEYS = (
    "_cell_length_a", "_cell_length_b", "_cell_length_c",
    "_cell_angle_alpha", "_cell_angle_beta", "_cell_angle_gamma",
)
COORD_KEYS = ("_atom_site_fract_x", "_atom_site_fract_y", "_atom_site_fract_z")
PYXPLORE_CIF_STAMP = (
    "# Generated by PyXplore WPEM StructureSolver\n"
    "# PyXplore diffraction-refinement software | https://pyxplore.netlify.app/"
)


def _number(value: object) -> float:
    """Read CIF values such as ``5.4321(2)``."""
    return float(str(value).split("(", 1)[0].strip("'\""))


def _read_pattern(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    data = pd.read_csv(path, header=None, comment="#")
    if data.shape[1] < 2:
        raise ValueError("The intensity CSV must contain 2theta and intensity columns.")
    values = data.iloc[:, :2].apply(pd.to_numeric, errors="coerce").dropna().to_numpy(float)
    if len(values) < 10:
        raise ValueError("The intensity CSV contains too few numeric points.")
    values = values[np.argsort(values[:, 0])]
    if np.any(np.diff(values[:, 0]) <= 0):
        raise ValueError("2theta values must be strictly increasing.")
    return values[:, 0], np.maximum(values[:, 1], 0.0)


def select_strong_peaks(two_theta: np.ndarray, intensity: np.ndarray,
                        num_peaks: Optional[int] = None) -> np.ndarray:
    """Return resolved high-intensity experimental peak indices.

    Without a requested count, prominence is derived from the MAD noise level
    and between 6 and 16 strongest resolved peaks are retained.
    """
    step = float(np.median(np.diff(two_theta)))
    noise = 1.4826 * np.median(np.abs(np.diff(intensity) - np.median(np.diff(intensity))))
    dynamic_range = float(np.ptp(intensity))
    prominence = max(5.0 * noise, 0.03 * dynamic_range, np.finfo(float).eps)
    distance = max(1, int(round(0.12 / step)))
    peaks, props = find_peaks(intensity, prominence=prominence, distance=distance)
    if not len(peaks):
        raise ValueError("No resolved diffraction peaks were found in the intensity CSV.")
    order = peaks[np.argsort(intensity[peaks])[::-1]]
    if num_peaks is None:
        # A clear elbow in the ranked intensities avoids fitting a long tail of
        # weak/noisy maxima while retaining enough reflections for the cell.
        limit = min(16, len(order))
        normalized = intensity[order[:limit]] / max(intensity[order[0]], 1e-12)
        below = np.flatnonzero(normalized < 0.12)
        count = int(below[0]) if len(below) else limit
        count = min(limit, max(6, count))
    else:
        if not isinstance(num_peaks, int) or num_peaks < 1:
            raise ValueError("num_peaks must be a positive integer or None.")
        count = min(num_peaks, len(order))
    return np.sort(order[:count])


class StructureSolver:
    """Solve a CIF's cell and asymmetric coordinates from strong XRD peaks.

    The input CIF is only overwritten when all acceptance criteria pass.  A
    byte-for-byte backup is then placed in ``WPEMFittingResults``.
    """

    def __init__(self, intensity_file, cif_file, wavelength="CuKa", num_peaks=None,
                 work_dir=None, max_nfev=120, peak_tolerance=0.35,
                 min_improvement=0.02, coordinate_window=0.01,
                 cell_window=0.35):
        self.intensity_file = Path(intensity_file)
        self.cif_file = Path(cif_file)
        self.wavelength = wavelength
        self.num_peaks = num_peaks
        self.work_dir = Path(work_dir) if work_dir is not None else self.cif_file.parent
        self.max_nfev = int(max_nfev)
        self.peak_tolerance = float(peak_tolerance)
        self.min_improvement = float(min_improvement)
        self.coordinate_window = float(coordinate_window)
        self.cell_window = float(cell_window)

    def solve(self) -> Dict[str, object]:
        if not self.intensity_file.is_file():
            raise FileNotFoundError("Intensity file not found: {}".format(self.intensity_file))
        if not self.cif_file.is_file():
            raise FileNotFoundError("CIF file not found: {}".format(self.cif_file))
        if self.peak_tolerance <= 0 or self.coordinate_window <= 0:
            raise ValueError("peak_tolerance and coordinate_window must be positive.")
        if not 0 < self.cell_window < 0.8:
            raise ValueError("cell_window must be between 0 and 0.8.")

        x, y = _read_pattern(self.intensity_file)
        peak_indices = select_strong_peaks(x, y, self.num_peaks)
        observed_angles, observed_intensities = x[peak_indices], y[peak_indices]
        source_text = self.cif_file.read_text(encoding="utf-8", errors="replace")
        source_cif = CifFile.from_string(source_text)
        block_name, block = self._structural_block(source_cif)
        initial_cell = np.array([_number(block.data[key]) for key in CELL_KEYS], dtype=float)
        initial_coordinates = np.array(
            [[_number(block.data[key][site]) for key in COORD_KEYS]
             for site in range(len(block.data[COORD_KEYS[0]]))], dtype=float
        )
        crystal_system, target_sg = self._space_group(source_text)
        cell_encode, cell_decode, cell_lower, cell_upper = self._cell_parameterization(initial_cell, crystal_system)
        cell_parameter_count = len(cell_encode(initial_cell))
        initial_parameters = np.r_[cell_encode(initial_cell), initial_coordinates.ravel()]
        lower = np.r_[cell_lower, initial_coordinates.ravel() - self.coordinate_window]
        upper = np.r_[cell_upper, initial_coordinates.ravel() + self.coordinate_window]

        initial_score, initial_matches = self._score(
            initial_parameters, source_cif, block_name, cell_decode, observed_angles, observed_intensities,
            initial_coordinates, cell_parameter_count,
        )
        best_frame_score = [float('inf')]
        frame_count = [0]
        def residual(parameters):
            score, _ = self._score(
                parameters, source_cif, block_name, cell_decode, observed_angles, observed_intensities,
                initial_coordinates, cell_parameter_count,
            )
            objective = float(np.mean(score ** 2))
            callback = getattr(self, 'frame_callback', None)
            if callback and objective < best_frame_score[0] * (1 - 1e-5):
                best_frame_score[0] = objective
                frame_count[0] += 1
                text = self._render(source_cif, block_name, cell_decode(parameters), parameters[cell_parameter_count:])
                angles, intensities = self._pattern(text)
                callback(text, angles, intensities, objective, frame_count[0])
            return score

        result = least_squares(residual, initial_parameters, bounds=(lower, upper),
                               max_nfev=self.max_nfev, method="trf")
        final_residual, final_matches = self._score(
            result.x, source_cif, block_name, cell_decode, observed_angles, observed_intensities,
            initial_coordinates, cell_parameter_count,
        )
        final_score = float(np.mean(final_residual ** 2))
        initial_score_value = float(np.mean(initial_score ** 2))
        candidate = self._render(source_cif, block_name, cell_decode(result.x), result.x[cell_parameter_count:])
        candidate_system, candidate_sg = self._space_group(candidate)
        improvement = (initial_score_value - final_score) / max(initial_score_value, 1e-12)
        matched_fraction = len(final_matches) / len(observed_angles)
        accepted = bool(
            result.success and candidate_sg == target_sg and candidate_system == crystal_system
            and matched_fraction >= 0.70 and improvement >= self.min_improvement
        )
        report = {
            "accepted": accepted,
            "reason": self._decision_reason(result.success, candidate_sg == target_sg,
                                              candidate_system == crystal_system, matched_fraction,
                                              improvement, self.min_improvement),
            "input_cif": str(self.cif_file), "intensity_file": str(self.intensity_file),
            "space_group_number": target_sg, "crystal_system": crystal_system,
            "selected_peak_count": int(len(observed_angles)),
            "selected_peaks_2theta": [float(value) for value in observed_angles],
            "initial_score": initial_score_value, "final_score": final_score,
            "improvement": float(improvement), "matched_fraction": float(matched_fraction),
            "initial_cell": initial_cell.tolist(), "solved_cell": cell_decode(result.x).tolist(),
            "optimizer_success": bool(result.success), "optimizer_message": str(result.message),
        }
        output_dir = self.work_dir / "WPEMFittingResults"
        output_dir.mkdir(parents=True, exist_ok=True)
        report_path = output_dir / "structure_solver_report.json"
        # Preserve the best numerical candidate for inspection or use as a
        # manual starting model even when the safety acceptance gate rejects
        # it. The original input CIF is never touched in that case.
        candidate_path = self._candidate_path(output_dir)
        candidate_path.write_text(candidate, encoding="utf-8")
        report["report_file"] = str(report_path)
        report["candidate_cif"] = str(candidate_path)
        if accepted:
            backup_path = self._backup_path(output_dir)
            shutil.copy2(self.cif_file, backup_path)
            self.cif_file.write_text(candidate, encoding="utf-8")
            report["backup_cif"] = str(backup_path)
            report["overwritten_cif"] = str(self.cif_file)
        report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        return report

    @staticmethod
    def _structural_block(cif: CifFile):
        for name, block in cif.data.items():
            if all(key in block.data for key in CELL_KEYS + COORD_KEYS):
                return name, block
        raise ValueError("CIF must contain cell constants and fractional atom-site coordinates.")

    def _space_group(self, cif_text: str) -> Tuple[str, int]:
        try:
            from pymatgen.io.cif import CifParser
            from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
            parser = CifParser.from_str(cif_text)
            # pymatgen 2024.x accesses spglib's dataset through its deprecated
            # dict interface internally. Limit suppression to that known
            # third-party warning and this single space-group calculation.
            with warnings.catch_warnings():
                warnings.filterwarnings(
                    "ignore", category=DeprecationWarning,
                    message=r"dict interface is deprecated\. Use attribute interface instead",
                    module=r"pymatgen\.symmetry\.analyzer",
                )
                warnings.filterwarnings(
                    "ignore", category=UserWarning,
                    message=(r"Issues encountered while parsing CIF: .*fractional "
                             r"coordinates rounded to ideal values to avoid issues "
                             r"with finite precision\."),
                    module=r"pymatgen\.io\.cif",
                )
                structure = parser.parse_structures(primitive=False)[0]
                analyzer = SpacegroupAnalyzer(structure, symprec=1e-3, angle_tolerance=5)
                return analyzer.get_crystal_system(), int(analyzer.get_space_group_number())
        except Exception as exc:
            raise ValueError("Could not read the CIF with pymatgen: {}".format(exc)) from exc

    def _pattern(self, cif_text: str):
        from pymatgen.analysis.diffraction.xrd import XRDCalculator
        from pymatgen.io.cif import CifParser
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore", category=UserWarning,
                message=(r"Issues encountered while parsing CIF: .*fractional "
                         r"coordinates rounded to ideal values to avoid issues "
                         r"with finite precision\."),
                module=r"pymatgen\.io\.cif",
            )
            structure = CifParser.from_str(cif_text).parse_structures(primitive=False)[0]
        calculator = XRDCalculator(wavelength=self.wavelength)
        pattern = calculator.get_pattern(structure, two_theta_range=(0, 180))
        return np.asarray(pattern.x, float), np.asarray(pattern.y, float)

    def _score(self, parameters, source_cif, block_name, decode, observed_angles,
               observed_intensities, initial_coordinates, cell_parameter_count):
        try:
            text = self._render(source_cif, block_name, decode(parameters), parameters[cell_parameter_count:])
        except Exception:
            return np.full(len(observed_angles) * 2, 1e6), []
        return self._score_rendered(text, observed_angles, observed_intensities, initial_coordinates, parameters)

    def _score_rendered(self, text, observed_angles, observed_intensities, initial_coordinates, parameters):
        try:
            calc_angles, calc_intensities = self._pattern(text)
            matches = []
            positions, intensities = [], []
            for angle, intensity in zip(observed_angles, observed_intensities):
                index = int(np.argmin(np.abs(calc_angles - angle)))
                delta = float(calc_angles[index] - angle)
                if abs(delta) <= self.peak_tolerance:
                    matches.append(index)
                # Keep the position residual continuous even before a peak is
                # within the acceptance tolerance; otherwise a moderately
                # inaccurate starting cell has a zero numerical gradient.
                positions.append(np.clip(delta / self.peak_tolerance, -12.0, 12.0))
                intensities.append(float(calc_intensities[index]))
            obs = observed_intensities / max(float(np.max(observed_intensities)), 1e-12)
            pred = np.asarray(intensities) / max(float(np.max(calc_intensities)), 1e-12)
            coordinate_count = initial_coordinates.size
            coordinate_parameters = parameters[-coordinate_count:]
            regularization = 0.25 * (coordinate_parameters - initial_coordinates.ravel()) / self.coordinate_window
            return np.r_[4.0 * np.asarray(positions), obs - pred, regularization], matches
        except Exception:
            return np.full(len(observed_angles) * 2 + initial_coordinates.size, 1e6), []

    def _cell_parameterization(self, cell, system):
        # Each decode enforces the metric restrictions of the original crystal
        # system, so changing the unit cell cannot lower the space-group lattice.
        length_lower, length_upper = 1.0 - self.cell_window, 1.0 + self.cell_window
        # Angle variations are relevant only for monoclinic, rhombohedral, and
        # triclinic metrics. Keep them much tighter than cell lengths.
        angle_lower, angle_upper = 0.90, 1.10
        if system == "cubic":
            return (lambda c: c[:1], lambda p: np.array([p[0], p[0], p[0], 90, 90, 90.]),
                    np.array([cell[0] * length_lower]), np.array([cell[0] * length_upper]))
        if system in ("tetragonal", "hexagonal"):
            gamma = 120. if system == "hexagonal" else 90.
            return (lambda c: c[[0, 2]], lambda p: np.array([p[0], p[0], p[1], 90, 90, gamma]),
                    cell[[0, 2]] * length_lower, cell[[0, 2]] * length_upper)
        if system == "orthorhombic":
            return (lambda c: c[:3], lambda p: np.array([p[0], p[1], p[2], 90, 90, 90.]),
                    cell[:3] * length_lower, cell[:3] * length_upper)
        if system == "monoclinic":
            return (lambda c: c[[0, 1, 2, 4]], lambda p: np.array([p[0], p[1], p[2], 90, p[3], 90.]),
                    cell[[0, 1, 2, 4]] * np.array([length_lower, length_lower, length_lower, angle_lower]),
                    cell[[0, 1, 2, 4]] * np.array([length_upper, length_upper, length_upper, angle_upper]))
        if system == "trigonal":
            # Trigonal structures are commonly written in either a hexagonal
            # setting (a=b, alpha=beta=90, gamma=120) or a rhombohedral
            # setting (a=b=c, alpha=beta=gamma).  Both must be constrained;
            # treating six cell values as independent incorrectly lowers R-3m
            # and similar space groups during optimization.
            hexagonal_setting = (
                np.isclose(cell[0], cell[1], rtol=1e-4)
                and np.isclose(cell[3], 90., atol=1e-3)
                and np.isclose(cell[4], 90., atol=1e-3)
                and np.isclose(cell[5], 120., atol=1e-3)
            )
            if hexagonal_setting:
                return (
                    lambda c: c[[0, 2]],
                    lambda p: np.array([p[0], p[0], p[1], 90., 90., 120.]),
                    cell[[0, 2]] * length_lower,
                    cell[[0, 2]] * length_upper,
                )
            return (
                lambda c: c[[0, 3]],
                lambda p: np.array([p[0], p[0], p[0], p[1], p[1], p[1]]),
                cell[[0, 3]] * np.array([length_lower, angle_lower]),
                cell[[0, 3]] * np.array([length_upper, angle_upper]),
            )
        # Triclinic cells have no lattice-metric restrictions.
        return (lambda c: c, lambda p: np.asarray(p[:6], float),
                cell * np.array([length_lower, length_lower, length_lower, angle_lower, angle_lower, angle_lower]),
                cell * np.array([length_upper, length_upper, length_upper, angle_upper, angle_upper, angle_upper]))

    def _render(self, source_cif, block_name, cell, coordinate_parameters):
        cif = copy.deepcopy(source_cif)
        # CifFile defaults to a third-party generator comment. All CIFs
        # produced by StructureSolver carry the PyXplore/WPEM provenance stamp.
        cif.comment = PYXPLORE_CIF_STAMP
        block = cif.data[block_name]
        for key, value in zip(CELL_KEYS, cell):
            block.data[key] = "{:.8f}".format(float(value))
        coordinates = np.asarray(coordinate_parameters, float).reshape((-1, 3)) % 1.0
        for axis, key in enumerate(COORD_KEYS):
            block.data[key] = ["{:.8f}".format(value) for value in coordinates[:, axis]]
        return str(cif)

    @staticmethod
    def _decision_reason(success, same_sg, same_system, matched_fraction, improvement,
                         min_improvement):
        if not success:
            return "optimizer did not converge"
        if not same_sg or not same_system:
            return "candidate does not preserve the input space group"
        if matched_fraction < .70:
            return "fewer than 70% of selected peaks match calculated reflections"
        if improvement < min_improvement:
            return "fit score did not improve by the required {:.1%}".format(min_improvement)
        return "accepted"

    def _backup_path(self, output_dir: Path) -> Path:
        base = output_dir / "{}_before_structure_solver.cif".format(self.cif_file.stem)
        if not base.exists():
            return base
        index = 2
        while True:
            candidate = output_dir / "{}_before_structure_solver_{}.cif".format(self.cif_file.stem, index)
            if not candidate.exists():
                return candidate
            index += 1

    def _candidate_path(self, output_dir: Path) -> Path:
        """Choose a non-overwriting path for every best candidate CIF."""
        base = output_dir / "{}_structure_solver_best.cif".format(self.cif_file.stem)
        if not base.exists():
            return base
        index = 2
        while True:
            candidate = output_dir / "{}_structure_solver_best_{}.cif".format(
                self.cif_file.stem, index
            )
            if not candidate.exists():
                return candidate
            index += 1


def solve_structure(intensity_file, cif_file, **kwargs) -> Dict[str, object]:
    """Convenience function exported from :mod:`PyXplore.WPEM`."""
    return StructureSolver(intensity_file, cif_file, **kwargs).solve()
