import { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { TransformControls } from "three/examples/jsm/controls/TransformControls.js";
import type { Atom, Structure } from "../formats";
import { minimumImageDisplacement, minimumImageDistance } from "../periodic";

export type EditorMode = "select" | "box" | "measure" | "add" | "translate" | "rotate" | "scale";
export type CameraView = "iso" | "x" | "y" | "z";
export type CameraProjection = "perspective" | "orthographic";
type Props = { structure: Structure; mode: EditorMode; cameraView: CameraView; projection: CameraProjection; cameraNonce: number; onSelect: (ids: number[]) => void; onMeasure: (ids: number[]) => void; onHover: (id: number | null) => void; onAdd: (position: { x: number; y: number; z: number }) => void; onTransform: (atoms: Atom[]) => void };
const TRANSFORM_MODES = new Set<EditorMode>(["translate", "rotate", "scale"]);
const COLORS: Record<string, number> = { H: 0xffffff, C: 0x404040, N: 0x3050f8, O: 0xff0d0d, F: 0x90e050, P: 0xff8000, S: 0xffff30, Cl: 0x1ff01f, Si: 0xf0c8a0, Fe: 0xe06633, Cu: 0xc88033, Zn: 0x7d80b0, Au: 0xffd123 };
const RADII: Record<string, number> = { H: .31, C: .77, N: .75, O: .73, F: .71, P: 1.06, S: 1.02, Cl: .99, Si: 1.17, Fe: 1.25, Cu: 1.28, Zn: 1.24, Au: 1.44 };
const radius = (symbol: string) => (RADII[symbol] ?? 1.2) * .55;

function centroid(atoms: Atom[]) {
  if (!atoms.length) return new THREE.Vector3();
  return atoms.reduce((sum, atom) => sum.add(new THREE.Vector3(atom.x, atom.y, atom.z)), new THREE.Vector3()).multiplyScalar(1 / atoms.length);
}

/** A self-contained Three.js editor. Persistent state always returns through OAW document actions. */
export function StructureViewport({ structure, mode, cameraView, projection, cameraNonce, onSelect, onMeasure, onHover, onAdd, onTransform }: Props) {
  const mount = useRef<HTMLDivElement>(null);
  const latest = useRef({ structure, mode, cameraView, projection, onSelect, onMeasure, onHover, onAdd, onTransform });
  const cameraPose = useRef<{ view: CameraView; projection: CameraProjection; nonce: number; position: number[]; quaternion: number[]; target: number[]; zoom: number } | null>(null);
  latest.current = { structure, mode, cameraView, projection, onSelect, onMeasure, onHover, onAdd, onTransform };

  useEffect(() => {
    const host = mount.current; if (!host) return;
    const scene = new THREE.Scene(); scene.background = new THREE.Color(0x181818);
    const camera = projection === "perspective" ? new THREE.PerspectiveCamera(45, 1, .01, 1000) : new THREE.OrthographicCamera(-1, 1, 1, -1, .01, 1000); camera.up.set(0, 0, 1);
    const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 1.5)); host.appendChild(renderer.domElement);
    const orbit = new OrbitControls(camera, renderer.domElement); orbit.enableDamping = true; orbit.dampingFactor = .1; orbit.screenSpacePanning = true;
    scene.add(new THREE.AmbientLight(0xffffff, .55)); const key = new THREE.DirectionalLight(0xffffff, .85); key.position.set(5, 10, 8); scene.add(key); const fill = new THREE.DirectionalLight(0xffffff, .25); fill.position.set(-5, -3, -6); scene.add(fill);
    const atomsGroup = new THREE.Group(); const bondsGroup = new THREE.Group(); const cellGroup = new THREE.Group(); scene.add(bondsGroup, atomsGroup, cellGroup);
    const pivot = new THREE.Object3D(); scene.add(pivot); const gizmo = new TransformControls(camera, renderer.domElement); const gizmoHelper = gizmo.getHelper(); scene.add(gizmoHelper);
    const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); const overlay = document.createElement("div"); overlay.className = "atomsculptor-box-overlay"; host.appendChild(overlay);
    let meshes: THREE.Mesh[] = []; let displayedAtoms: Atom[] = []; let midpoint = new THREE.Vector3(); let press: { x: number; y: number; additive: boolean; boxSelect: boolean } | null = null; let boxStart: { x: number; y: number; additive: boolean } | null = null; let measured: number[] = []; let transformStart: Map<number, Atom> | null = null; let pivotStart = new THREE.Vector3(); let transformDirty = false; let gizmoDragging = false; let viewRadius = 8; let hovered: number | null = null;

    const disposeGroup = (group: THREE.Group) => { while (group.children.length) { const object = group.children.pop(); object?.traverse(node => { if (node instanceof THREE.Mesh || node instanceof THREE.LineSegments) { node.geometry.dispose(); const materials = Array.isArray(node.material) ? node.material : [node.material]; materials.forEach(material => material.dispose()); } }); } };
    const renderedPosition = (atom: Atom) => new THREE.Vector3(atom.x, atom.y, atom.z).sub(midpoint);
    const configureGizmo = () => {
      const selected = latest.current.structure.atoms.filter(atom => latest.current.structure.selected_atom_ids.includes(atom.id) && displayedAtoms.some(visible => visible.id === atom.id));
      if (!TRANSFORM_MODES.has(latest.current.mode) || !selected.length) { gizmo.detach(); gizmoHelper.visible = false; return; }
      pivot.position.copy(centroid(selected).sub(midpoint)); pivot.quaternion.identity(); pivot.scale.set(1, 1, 1); gizmo.setMode(latest.current.mode as "translate" | "rotate" | "scale"); gizmo.attach(pivot); gizmoHelper.visible = true;
    };
    const draw = () => {
      disposeGroup(atomsGroup); disposeGroup(bondsGroup); disposeGroup(cellGroup);
      const current = latest.current.structure; const visibleLayers = new Set(current.layers.filter(layer => layer.visible).map(layer => layer.id)); displayedAtoms = current.atoms.filter(atom => visibleLayers.has(atom.layer_id)); midpoint = centroid(displayedAtoms); const selected = new Set(current.selected_atom_ids);
      meshes = displayedAtoms.map(atom => { const material = new THREE.MeshPhongMaterial({ color: COLORS[atom.symbol] ?? 0xff1493, emissive: selected.has(atom.id) ? 0x2080ff : 0, emissiveIntensity: selected.has(atom.id) ? .75 : 0, shininess: 70 }); const mesh = new THREE.Mesh(new THREE.SphereGeometry(radius(atom.symbol), 28, 20), material); mesh.position.copy(renderedPosition(atom)); mesh.userData.atomId = atom.id; atomsGroup.add(mesh); return mesh; });
      const addBond = (first: Atom, second: Atom, explicit = false) => { const start = renderedPosition(first); const delta = minimumImageDisplacement(first, second, current); const end = start.clone().add(new THREE.Vector3(delta.x, delta.y, delta.z)); const distance = minimumImageDistance(first, second, current); if (distance <= 0 || (!explicit && distance >= (radius(first.symbol) + radius(second.symbol)) * 2.3)) return; const bond = new THREE.Mesh(new THREE.CylinderGeometry(.055, .055, distance, 10), new THREE.MeshPhongMaterial({ color: 0xaaaaaa })); bond.position.copy(start).lerp(end, .5); bond.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), end.clone().sub(start).normalize()); bondsGroup.add(bond); };
      if (current.bonds?.length) { const byId = new Map(displayedAtoms.map(atom => [atom.id, atom])); for (const bond of current.bonds) { const first = byId.get(bond.first_atom_id); const second = byId.get(bond.second_atom_id); if (first && second) addBond(first, second, true); } } else for (let i = 0; i < displayedAtoms.length; i += 1) for (let j = i + 1; j < displayedAtoms.length; j += 1) addBond(displayedAtoms[i], displayedAtoms[j]);
      if (current.cell) { const [a, b, c] = current.cell.map(row => new THREE.Vector3(row[0], row[1], row[2])); const corners = [new THREE.Vector3(), a, b, c, a.clone().add(b), a.clone().add(c), b.clone().add(c), a.clone().add(b).add(c)].map(point => point.sub(midpoint)); const edges = [[0, 1], [0, 2], [0, 3], [1, 4], [1, 5], [2, 4], [2, 6], [3, 5], [3, 6], [4, 7], [5, 7], [6, 7]]; const points = edges.flatMap(([from, to]) => [corners[from], corners[to]]); const geometry = new THREE.BufferGeometry().setFromPoints(points); cellGroup.add(new THREE.LineSegments(geometry, new THREE.LineBasicMaterial({ color: 0x6c779d, transparent: true, opacity: .8 }))); }
      viewRadius = Math.max(3, ...displayedAtoms.map(atom => new THREE.Vector3(atom.x, atom.y, atom.z).distanceTo(midpoint))) * 1.9;
      const direction = latest.current.cameraView === "x" ? new THREE.Vector3(1, 0, 0) : latest.current.cameraView === "y" ? new THREE.Vector3(0, 1, 0) : latest.current.cameraView === "z" ? new THREE.Vector3(0, 0, 1) : new THREE.Vector3(1, 1, .7).normalize();
      if (camera instanceof THREE.OrthographicCamera) { camera.left = -viewRadius; camera.right = viewRadius; camera.top = viewRadius; camera.bottom = -viewRadius; camera.updateProjectionMatrix(); }
      camera.position.copy(direction.multiplyScalar(viewRadius)); orbit.target.set(0, 0, 0); orbit.update(); configureGizmo();
    };
    const resize = () => { const width = Math.max(1, host.clientWidth); const height = Math.max(1, host.clientHeight); if (camera instanceof THREE.PerspectiveCamera) camera.aspect = width / height; else { const aspect = width / height; camera.left = -viewRadius * aspect; camera.right = viewRadius * aspect; camera.top = viewRadius; camera.bottom = -viewRadius; } camera.updateProjectionMatrix(); renderer.setSize(width, height, false); };
    const restoreCameraPose = () => { const saved = cameraPose.current; if (!saved || saved.view !== cameraView || saved.projection !== projection || saved.nonce !== cameraNonce) return; camera.position.fromArray(saved.position); camera.quaternion.fromArray(saved.quaternion); camera.zoom = saved.zoom; orbit.target.fromArray(saved.target); camera.updateProjectionMatrix(); orbit.update(); };
    const observer = new ResizeObserver(resize); observer.observe(host); resize(); draw(); restoreCameraPose();
    const hitAtom = (event: PointerEvent) => { const bounds = renderer.domElement.getBoundingClientRect(); pointer.x = ((event.clientX - bounds.left) / bounds.width) * 2 - 1; pointer.y = -((event.clientY - bounds.top) / bounds.height) * 2 + 1; raycaster.setFromCamera(pointer, camera); return raycaster.intersectObjects(meshes, false)[0]?.object.userData.atomId as number | undefined; };
    const updateOverlay = (event: PointerEvent) => { if (!boxStart) return; const bounds = renderer.domElement.getBoundingClientRect(); const x = Math.min(boxStart.x, event.clientX - bounds.left); const y = Math.min(boxStart.y, event.clientY - bounds.top); overlay.style.cssText = `display:block;left:${x}px;top:${y}px;width:${Math.abs(event.clientX - bounds.left - boxStart.x)}px;height:${Math.abs(event.clientY - bounds.top - boxStart.y)}px`; };
    const finishBox = (event: PointerEvent) => { if (!boxStart) return false; const bounds = renderer.domElement.getBoundingClientRect(); const endX = event.clientX - bounds.left; const endY = event.clientY - bounds.top; const width = Math.abs(endX - boxStart.x); const height = Math.abs(endY - boxStart.y); overlay.style.display = "none"; if (width < 4 && height < 4) { boxStart = null; orbit.enabled = true; return false; } const left = Math.min(boxStart.x, endX); const right = Math.max(boxStart.x, endX); const top = Math.min(boxStart.y, endY); const bottom = Math.max(boxStart.y, endY); const ids = boxStart.additive ? [...latest.current.structure.selected_atom_ids] : []; for (const mesh of meshes) { const p = mesh.position.clone().project(camera); const x = (p.x + 1) * .5 * bounds.width; const y = (1 - p.y) * .5 * bounds.height; if (x >= left && x <= right && y >= top && y <= bottom) { const id = mesh.userData.atomId as number; if (!ids.includes(id)) ids.push(id); } } boxStart = null; orbit.enabled = true; latest.current.onSelect(ids); return true; };
    const pointerDown = (event: PointerEvent) => { if (event.button !== 0 || gizmoDragging) return; const bounds = renderer.domElement.getBoundingClientRect(); const additive = event.shiftKey || event.metaKey || event.ctrlKey; const ownsPointer = latest.current.mode === "box" || (additive && latest.current.mode !== "measure"); if (ownsPointer) { event.preventDefault(); event.stopImmediatePropagation(); renderer.domElement.setPointerCapture(event.pointerId); } if (latest.current.mode === "box") { boxStart = { x: event.clientX - bounds.left, y: event.clientY - bounds.top, additive }; orbit.enabled = false; updateOverlay(event); return; } press = { x: event.clientX, y: event.clientY, additive, boxSelect: event.shiftKey }; };
    const pointerMove = (event: PointerEvent) => { if (boxStart) { event.preventDefault(); event.stopImmediatePropagation(); updateOverlay(event); return; } if (press && press.boxSelect && latest.current.mode !== "measure" && Math.hypot(event.clientX - press.x, event.clientY - press.y) > 4) { const bounds = renderer.domElement.getBoundingClientRect(); boxStart = { x: press.x - bounds.left, y: press.y - bounds.top, additive: press.additive }; press = null; orbit.enabled = false; event.preventDefault(); event.stopImmediatePropagation(); updateOverlay(event); return; } if (press || gizmoDragging) return; const id = hitAtom(event) ?? null; if (id !== hovered) { hovered = id; renderer.domElement.style.cursor = id === null ? "default" : "pointer"; latest.current.onHover(id); } };
    const pointerUp = (event: PointerEvent) => { if (renderer.domElement.hasPointerCapture(event.pointerId)) renderer.domElement.releasePointerCapture(event.pointerId); if (boxStart) { event.preventDefault(); event.stopImmediatePropagation(); finishBox(event); return; } const pointerPress = press; press = null; if (!pointerPress || Math.hypot(event.clientX - pointerPress.x, event.clientY - pointerPress.y) > 4 || gizmoDragging) return; const current = latest.current; if (current.mode === "add") { const bounds = renderer.domElement.getBoundingClientRect(); pointer.x = ((event.clientX - bounds.left) / bounds.width) * 2 - 1; pointer.y = -((event.clientY - bounds.top) / bounds.height) * 2 + 1; raycaster.setFromCamera(pointer, camera); const point = new THREE.Vector3(); if (raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0, 0, 1), 0), point)) current.onAdd({ x: point.x + midpoint.x, y: point.y + midpoint.y, z: point.z + midpoint.z }); return; } const atomId = hitAtom(event); if (current.mode === "measure") { if (atomId === undefined) return; measured = measured.length >= 2 ? [atomId] : [...measured, atomId]; current.onMeasure(measured); return; } if (atomId === undefined) { if (!pointerPress.additive) current.onSelect([]); return; } const prior = current.structure.selected_atom_ids; current.onSelect(pointerPress.additive ? (prior.includes(atomId) ? prior.filter(id => id !== atomId) : [...prior, atomId]) : [atomId]); };
    const projectedTransform = () => { if (!transformStart) return []; const rotation = pivot.quaternion.clone(); const scale = pivot.scale.clone(); return latest.current.structure.atoms.map(atom => { const initial = transformStart?.get(atom.id); if (!initial) return atom; const position = new THREE.Vector3(initial.x, initial.y, initial.z).sub(midpoint).sub(pivotStart).multiply(scale).applyQuaternion(rotation).add(pivot.position).add(midpoint); return { ...atom, x: position.x, y: position.y, z: position.z }; }); };
    gizmo.addEventListener("dragging-changed", event => { const dragging = (event as { value: boolean }).value; gizmoDragging = dragging; orbit.enabled = !dragging; if (dragging) { transformStart = new Map(latest.current.structure.atoms.filter(atom => latest.current.structure.selected_atom_ids.includes(atom.id)).map(atom => [atom.id, { ...atom }])); pivotStart = pivot.position.clone(); transformDirty = false; } else if (transformStart && transformDirty) { latest.current.onTransform(projectedTransform()); transformStart = null; } });
    gizmo.addEventListener("objectChange", () => { if (!transformStart) return; transformDirty = true; const changed = new Map(projectedTransform().map(atom => [atom.id, atom])); for (const mesh of meshes) { const atom = changed.get(mesh.userData.atomId as number); if (atom) mesh.position.copy(renderedPosition(atom)); } });
    const nudge = (event: KeyboardEvent) => { if (!TRANSFORM_MODES.has(latest.current.mode) || event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; const key = event.key.toLowerCase(); const direction = key === "arrowup" || key === "w" ? "up" : key === "arrowdown" || key === "s" ? "down" : key === "arrowleft" || key === "a" ? "left" : key === "arrowright" || key === "d" ? "right" : null; if (!direction) return; const selected = latest.current.structure.atoms.filter(atom => latest.current.structure.selected_atom_ids.includes(atom.id)); if (!selected.length) return; event.preventDefault(); const cameraDirection = new THREE.Vector3(); camera.getWorldDirection(cameraDirection); const up = camera.up.clone().normalize(); const right = new THREE.Vector3().crossVectors(cameraDirection, up).normalize(); const screenUp = new THREE.Vector3().crossVectors(right, cameraDirection).normalize(); const centre = centroid(selected); const next = latest.current.structure.atoms.map(atom => { if (!latest.current.structure.selected_atom_ids.includes(atom.id)) return atom; if (latest.current.mode === "translate") { const directionVector = direction === "up" ? screenUp.clone() : direction === "down" ? screenUp.clone().multiplyScalar(-1) : direction === "left" ? right.clone().multiplyScalar(-1) : right.clone(); const delta = directionVector.multiplyScalar(.1); return { ...atom, x: atom.x + delta.x, y: atom.y + delta.y, z: atom.z + delta.z }; } if (latest.current.mode === "scale") { const factor = direction === "up" || direction === "right" ? 1.02 : .98; return { ...atom, x: centre.x + (atom.x - centre.x) * factor, y: centre.y + (atom.y - centre.y) * factor, z: centre.z + (atom.z - centre.z) * factor }; } const axis = direction === "up" || direction === "down" ? right : screenUp; const angle = (direction === "up" || direction === "right" ? 1 : -1) * Math.PI / 180; const point = new THREE.Vector3(atom.x, atom.y, atom.z).sub(centre).applyAxisAngle(axis, angle).add(centre); return { ...atom, x: point.x, y: point.y, z: point.z }; }); latest.current.onTransform(next); };
    renderer.domElement.addEventListener("pointerdown", pointerDown, true); renderer.domElement.addEventListener("pointermove", pointerMove, true); renderer.domElement.addEventListener("pointerup", pointerUp, true); renderer.domElement.addEventListener("pointerleave", () => { if (hovered !== null) { hovered = null; latest.current.onHover(null); } }); window.addEventListener("keydown", nudge); renderer.setAnimationLoop(() => { orbit.update(); renderer.render(scene, camera); });
    return () => { cameraPose.current = { view: cameraView, projection, nonce: cameraNonce, position: camera.position.toArray(), quaternion: camera.quaternion.toArray(), target: orbit.target.toArray(), zoom: camera.zoom }; observer.disconnect(); renderer.setAnimationLoop(null); renderer.domElement.removeEventListener("pointerdown", pointerDown, true); renderer.domElement.removeEventListener("pointermove", pointerMove, true); renderer.domElement.removeEventListener("pointerup", pointerUp, true); window.removeEventListener("keydown", nudge); gizmo.dispose(); orbit.dispose(); disposeGroup(atomsGroup); disposeGroup(bondsGroup); disposeGroup(cellGroup); overlay.remove(); renderer.dispose(); renderer.domElement.remove(); };
  }, [structure, mode, cameraView, projection, cameraNonce]);
  return <div className="atomsculptor-legacy-viewport nodrag nopan nowheel" ref={mount} />;
}
