import { expect, test } from "@playwright/test";

test("drop an Agent or Legion into barracks without moving the source graph", async ({ page, request }) => {
  await page.setViewportSize({ width: 2200, height: 1800 });
  const create = async (type: string, name: string, x: number, y: number) => (await request.post("/api/nodes", { data: { type, name, position: { x, y } } })).json();
  const library = await create("oaw.barracks", "Drop barracks", 1100, 250);
  const agent = await create("agent", "Dropped worker", 150, 350);
  const resource = await create("text", "Worker brief", 500, 350);
  const peer = await create("agent", "Team entry", 450, 1100);
  const group = (await (await request.post("/api/legion-groups", { data: { name: "Dropped team", node_ids: [peer.id] } })).json())[0];
  const connection = await (await request.post("/api/edges", { data: { source: agent.id, target: resource.id, relationship: "read" } })).json();
  const read = async (id: string) => (await request.get(`/api/nodes/${id}`)).json();
  const memberBefore = await read(peer.id);
  await page.goto("/");
  const frame = page.locator(`[data-card-id="${library.id}"]`);
  const editor = page.getByRole("dialog", { name: "Drop barracks workspace", exact: true });
  const dragInto = async (id: string, headerX = 30) => {
    const source = (await page.locator(`[data-card-id="${id}"]`).boundingBox())!;
    const target = (await frame.boundingBox())!;
    await page.mouse.move(source.x + headerX, source.y + 30);
    await page.mouse.down();
    await page.mouse.move(target.x + 350, target.y + 240, { steps: 20 });
    await page.mouse.up();
    await expect(editor.getByRole("heading", { name: "Save callable template", exact: true })).toBeVisible();
  };
  await dragInto(agent.id);
  await expect(editor.getByRole("textbox", { name: "Template name", exact: true })).toHaveValue("Dropped worker");
  await expect(editor.getByRole("checkbox", { name: "Dropped worker agent", exact: true })).toBeChecked();
  await expect(editor.getByRole("combobox", { name: "Entry Agent", exact: true })).toHaveValue(agent.id);
  await editor.getByRole("button", { name: "Cancel", exact: true }).click();
  expect((await read(agent.id)).position).toEqual(agent.position);
  expect((await (await request.get(`/api/nodes/${library.id}/summoning`)).json()).templates).toHaveLength(0);
  await editor.getByRole("button", { name: "Close barracks", exact: true }).click();
  await dragInto(agent.id);
  await editor.getByRole("combobox", { name: "Binding for Worker brief", exact: true }).selectOption("share");
  await editor.getByRole("button", { name: "Save template", exact: true }).click();
  await expect(editor.locator(".barracks-templates")).toContainText("Dropped worker");
  expect((await read(agent.id)).position).toEqual(agent.position);
  expect((await read(agent.id)).parent_id).toBeNull();
  const world = await (await request.get("/api/world")).json();
  expect(world.edges.find((edge: { id: string }) => edge.id === connection.id)).toEqual(connection);
  await editor.getByRole("button", { name: "Close barracks", exact: true }).click();
  await dragInto(group.id, 250);
  await expect(editor.getByRole("textbox", { name: "Template name", exact: true })).toHaveValue("Dropped team");
  await expect(editor.getByRole("combobox", { name: "Entry Agent", exact: true })).toHaveValue(peer.id);
  await editor.getByRole("button", { name: "Save template", exact: true }).click();
  await expect(editor.locator(".barracks-templates")).toContainText("Dropped team");
  expect((await read(group.id)).position).toEqual(group.position);
  expect((await read(peer.id)).position).toEqual(memberBefore.position);
  expect((await read(peer.id)).parent_id).toBe(group.id);
  await page.screenshot({ path: "../.open-agent-world/barracks-drop.png" });
  const templates = (await (await request.get(`/api/nodes/${library.id}/summoning`)).json()).templates;
  await request.post("/api/nodes/batch-delete", { data: { node_ids: [library.id, agent.id, resource.id, group.id, peer.id, ...templates.map((t: { id: string }) => t.id)] } });
});

test("save an equipped Agent, summon, follow up and reclaim its retained instance", async ({ page, request }) => {
  await page.setViewportSize({ width: 1600, height: 1100 });
  const create = async (type: string, name: string, x: number, y: number) => {
    const response = await request.post("/api/nodes", { data: { type, name, position: { x, y } } });
    expect(response.status()).toBe(201);
    return response.json();
  };
  const barracks = await create("oaw.barracks", "Research barracks", 710, 430);
  const agent = await create("agent", "Research lead", 100, 180);
  const skills = await create("oaw.skills", "Shared research tools", 100, 1000);
  const sandbox = await create("sandbox", "Worker sandbox", 450, 180);
  for (const [target, relationship] of [[skills.id, "oaw.skills.use"], [sandbox.id, "execute"], [barracks.id, "oaw.barracks.summon"]]) {
    expect((await request.post("/api/edges", { data: { source: agent.id, target, relationship } })).status()).toBe(201);
  }
  await page.goto("/");
  const card = page.locator(`[data-card-id="${barracks.id}"]`);
  await card.getByRole("button", { name: "Open barracks", exact: true }).click();
  const box = page.getByRole("dialog", { name: "Research barracks workspace", exact: true });
  await box.getByRole("button", { name: "Barracks settings", exact: true }).click();
  await box.getByLabel("Instructions for connected Agents").fill("Summon a researcher when the task needs source verification.");
  await box.getByLabel("Maximum summon depth").fill("3");
  await box.getByRole("button", { name: "Save settings", exact: true }).click();
  await box.getByRole("button", { name: "Save selected as template", exact: true }).click();
  await box.getByLabel("Template name", { exact: true }).fill("Equipped researcher");
  await box.getByLabel("When to use", { exact: true }).fill("Use for research that needs scripts and reusable instructions.");
  await box.getByRole("checkbox", { name: "Research lead agent", exact: true }).check();
  await box.getByRole("combobox", { name: "Entry Agent", exact: true }).selectOption(agent.id);
  await box.getByLabel("Binding for Shared research tools").selectOption("share");
  await box.getByLabel("Binding for Worker sandbox").selectOption("copy");
  await expect(box.getByLabel("Binding for Research barracks")).toHaveValue("share");
  await page.screenshot({ path: "../.open-agent-world/barracks-capture.png" });
  await box.getByRole("button", { name: "Save template", exact: true }).click();
  await expect(box.locator(".barracks-templates")).toContainText("Equipped researcher");
  await expect(box.locator(".barracks-templates")).toContainText("2 copied nodes · 2 shared connections");
  await box.getByRole("textbox", { name: "Task / follow-up", exact: true }).fill("Verify the sources");
  await box.getByRole("button", { name: "Summon new instance", exact: true }).click();
  const instances = box.locator(".barracks-instances");
  await expect(instances).toContainText("succeeded");
  await instances.locator("summary").click();
  await expect(instances).toContainText("Mock response: Verify the sources");
  await page.screenshot({ path: "../.open-agent-world/barracks-result.png" });
  await box.getByRole("textbox", { name: "Task / follow-up", exact: true }).fill("Summarize the findings");
  await instances.getByRole("button", { name: "Follow up", exact: true }).click();
  await expect(instances).toContainText("Mock response: Summarize the findings");
  const snapshot = await (await request.get(`/api/nodes/${barracks.id}/summoning`)).json();
  expect(snapshot.instances).toHaveLength(1);
  expect(snapshot.instances[0].attempts).toHaveLength(2);
  await page.reload();
  await card.getByRole("button", { name: "Open barracks", exact: true }).click();
  await expect(instances).toContainText("succeeded");
  await instances.getByRole("button", { name: "Reclaim instance", exact: true }).click();
  await expect(instances).toContainText("reclaimed");
  expect((await request.get(`/api/nodes/${skills.id}`)).status()).toBe(200);
  expect((await request.get(`/api/nodes/${snapshot.instances[0].entry_agent_id}`)).status()).toBe(404);
  await box.getByRole("button", { name: "Close barracks", exact: true }).click();
  for (const id of [snapshot.templates[0].id, barracks.id, agent.id, sandbox.id, skills.id]) await request.delete(`/api/nodes/${id}`);
});
