import { expect, test } from "@playwright/test";
import type { LibrarySnapshot } from "../src/state/cardLibrary";

test("packs, collection and active decks persist and recover from plugin disable", async ({ page, request, context }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  const controls = page.getByRole("complementary", { name: "World status and controls" });
  await expect(controls.locator(".top-actions button")).toHaveCount(4);
  expect(await controls.evaluate(panel => {
    const box = panel.getBoundingClientRect();
    return [...panel.querySelectorAll("button")].every(button => { const rect = button.getBoundingClientRect(); return rect.left >= box.left && rect.right <= box.right && rect.top >= box.top && rect.bottom <= box.bottom; });
  })).toBe(true);
  const tray = page.getByRole("complementary", { name: "Active card deck" });
  await tray.hover();
  await expect(tray.getByText("Build your deck")).toBeVisible();
  await expect(tray.getByRole("button", { name: /^Place / })).toHaveCount(0);
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  const library = page.getByRole("dialog", { name: "Pack & Card Library" });
  const pack = library.getByRole("article", { name: "Core essentials", exact: true });
  await expect(pack).not.toHaveClass(/is-opened/);
  await expect(pack.getByRole("button")).toHaveCount(1);
  await expect(pack.locator("details")).toHaveCount(0);
  await expect(pack.locator(".pack-object")).toHaveCSS("transform-style", "preserve-3d");
  await expect(pack.locator(".pack-object")).toHaveCSS("--pack-depth", "26");
  const wrapper = pack.locator(".pack-touch-area");
  const hitArea = (await wrapper.boundingBox())!;
  expect(hitArea.width).toBeLessThan(220);
  await page.screenshot({ path: "../.tmp/library-foil-sealed.png" });
  await page.mouse.move(hitArea.x + 12, hitArea.y + 45);
  await expect(wrapper).toHaveAttribute("data-tilting", "true");
  const firstLight = await wrapper.evaluate(element => element.style.getPropertyValue("--light-x"));
  await page.mouse.move(hitArea.x + hitArea.width - 12, hitArea.y + 200);
  await expect.poll(() => wrapper.evaluate(element => element.style.getPropertyValue("--light-x"))).not.toBe(firstLight);
  expect(await wrapper.boundingBox()).toEqual(hitArea);
  await page.screenshot({ path: "../.tmp/library-foil-tilt.png" });
  await page.mouse.move(10, 10);
  await expect(wrapper).not.toHaveAttribute("data-tilting");
  await page.emulateMedia({ reducedMotion: "reduce" });
  await wrapper.hover();
  await expect(wrapper).not.toHaveAttribute("data-tilting");
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await wrapper.focus();
  await page.keyboard.press("Enter");
  await expect(library.getByRole("status")).toContainText("Core essentials opened");
  await expect(pack).toHaveClass(/is-opened/);
  await pack.evaluate(element => element.getAnimations({ subtree: true }).forEach(animation => { animation.pause(); animation.currentTime = 1220; }));
  const openingTop = await pack.locator(".pack-drawn-cards").evaluate(element => Math.min(...[...element.children].map(card => card.getBoundingClientRect().top)));
  expect(openingTop).toBeGreaterThan((await library.locator(".library-section-heading").boundingBox())!.y + 45);
  await page.screenshot({ path: "../.tmp/library-foil-opening.png" });
  await pack.evaluate(element => element.getAnimations({ subtree: true }).forEach(animation => animation.finish()));
  await pack.getByRole("button", { name: "View cards in Core essentials" }).click();
  await library.getByLabel("Search cards", { exact: true }).fill("Text file");
  await library.getByRole("button", { name: "Inspect Text file" }).click();
  await page.screenshot({ path: "../.tmp/library-paper-cards.png" });
  await expect(library.getByRole("complementary", { name: "Card details" })).toContainText("Core essentials");
  await library.getByRole("button", { name: "Add Text file to deck" }).click();
  await expect(library.getByRole("button", { name: "Remove Text file from deck" })).toBeVisible();
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Place Text file", exact: true })).toBeVisible();
  await expect(tray.getByRole("button", { name: "Place Agent", exact: true })).toHaveCount(0);
  await tray.getByRole("button", { name: "Place Text file", exact: true }).dragTo(page.locator(".react-flow__pane").first(), { targetPosition: { x: 420, y: 250 } });
  await expect.poll(async () => (await (await request.get("/api/nodes")).json()).some((node: { type: string }) => node.type === "text")).toBe(true);
  await page.keyboard.press("Control+z");
  await expect.poll(async () => (await (await request.get("/api/nodes")).json()).length).toBe(0);
  await page.keyboard.press("Control+Shift+z");
  await expect.poll(async () => (await (await request.get("/api/nodes")).json()).length).toBe(1);
  await page.reload();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Place Text file", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  await expect(pack).toHaveClass(/is-opened/);
  await expect(pack.locator(".pack-top-seal")).toHaveCSS("opacity", "0");
  await expect(pack.locator(".pack-object")).toHaveCSS("--pack-depth", "1");
  await expect(pack.locator(".pack-card-pocket")).toHaveCSS("visibility", "hidden");
  await page.screenshot({ path: "../.tmp/library-foil-empty.png" });
  await library.getByRole("button", { name: /^Cards/ }).click();
  await library.getByLabel("Source pack", { exact: true }).selectOption({ label: "Core essentials" });
  await library.getByRole("button", { name: "Remove Text file from deck" }).click();
  await expect(library.getByRole("button", { name: "Add Text file to deck" })).toBeVisible();
  await library.getByRole("button", { name: /^Decks/ }).click();
  await library.getByLabel("New deck name").fill("Research kit");
  await library.getByRole("button", { name: "Create deck", exact: true }).click();
  await expect(library.getByRole("heading", { name: "Research kit", exact: true })).toBeVisible();
  await expect(library.getByRole("button", { name: "Active deck", exact: true })).toBeDisabled();
  await library.getByRole("button", { name: /^Packs/ }).click();
  const taskPack = library.getByRole("article", { name: "Task Board", exact: true });
  await taskPack.getByRole("button", { name: "Tear open Task Board", exact: true }).click();
  await taskPack.getByRole("button", { name: "View cards in Task Board", exact: true }).click();
  await library.getByLabel("Search cards", { exact: true }).fill("Task Board");
  await library.getByRole("button", { name: "Add Task Board to deck" }).click();
  const sourceControls = library.getByLabel("Source pack controls");
  await sourceControls.getByRole("button", { name: "Disable plugin" }).click();
  await expect(sourceControls).toContainText("Plugin disabled");
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Task Board unavailable" })).toBeDisabled();
  await expect(tray.getByRole("button", { name: "Place Text file", exact: true })).toHaveCount(0);
  await page.reload();
  await tray.hover();
  await expect(tray.getByRole("tab", { name: /Research kit/ })).toHaveAttribute("aria-selected", "true");
  await expect(tray.getByRole("button", { name: "Task Board unavailable" })).toBeDisabled();
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  await taskPack.getByRole("button", { name: "View cards in Task Board", exact: true }).click();
  await sourceControls.getByRole("button", { name: "Enable plugin" }).click();
  await expect(sourceControls).toContainText("Installed · Enabled");
  await library.getByRole("button", { name: /^Store/ }).click();
  await expect(library.getByText("Coming later", { exact: true })).toBeVisible();
  await page.screenshot({ path: "../.tmp/library-store.png" });
  await library.getByRole("button", { name: /^Packs/ }).click();
  await page.screenshot({ path: "../.tmp/library-packs.png" });
  await library.getByRole("button", { name: /^Cards/ }).click();
  await page.screenshot({ path: "../.tmp/library-cards.png" });
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Place Task Board", exact: true })).toBeEnabled();
  // A second window receives an authoritative deck change over the event stream.
  const other = await context.newPage();
  await other.goto("/");
  await other.getByRole("complementary", { name: "Active card deck" }).hover();
  await expect(other.getByRole("button", { name: "Place Task Board", exact: true })).toBeEnabled();
  const state = await (await request.get("/api/card-library")).json();
  const response = await request.post("/api/card-library/actions", { data: { action: "update_deck", id: state.active_deck_id, entries: [], expected_revision: state.revision } });
  expect(response.ok()).toBe(true);
  await expect(other.getByRole("button", { name: "Place Task Board", exact: true })).toHaveCount(0);
  await expect(tray.getByRole("button", { name: "Place Task Board", exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 640, height: 780 });
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  await page.screenshot({ path: "../.tmp/library-narrow.png" });
  expect(await library.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await library.getByRole("button", { name: /^Packs/ }).click();
  await library.getByLabel("Search packs").fill("");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../.tmp/library-foil-mobile.png" });
  expect(await library.locator(".library-body").evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await page.setViewportSize({ width: 640, height: 780 });
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.getByRole("button", { name: "Create a new card deck" }).click();
  await tray.getByLabel("Deck name", { exact: true }).fill("Quick tools");
  await tray.getByLabel("Deck icon", { exact: true }).selectOption("zap");
  await page.screenshot({ path: "../.tmp/deck-create-controls.png" });
  await tray.getByRole("button", { name: "Create deck", exact: true }).click();
  await expect(tray.getByRole("tab", { name: /Quick tools/ }).locator("svg")).toHaveClass(/lucide-zap/);
  await page.reload();
  await expect(tray.getByRole("tab", { name: /Quick tools/ }).locator("svg")).toHaveClass(/lucide-zap/);
  await expect(tray.getByRole("tab", { name: /Research kit/ }).locator("svg")).toHaveClass(/lucide-folder/);
  expect(await controls.evaluate(panel => {
    const box = panel.getBoundingClientRect();
    return [...panel.querySelectorAll("button")].every(button => { const rect = button.getBoundingClientRect(); return rect.left >= box.left && rect.right <= box.right && rect.top >= box.top && rect.bottom <= box.bottom; });
  })).toBe(true);
  await page.screenshot({ path: "../.tmp/deck-controls-fixed.png" });
  expect(errors).toEqual([]);
});

test("source packs organize the collection and scoped Skills lead to their usable containers", async ({ page, request }) => {
  test.setTimeout(60000);
  let snapshot: LibrarySnapshot = await (await request.get("/api/card-library")).json();
  for (const id of snapshot.available_pack_ids) {
    const result = await request.post("/api/card-library/actions", { data: { action: "open_pack", id, expected_revision: snapshot.revision } });
    expect(result.ok()).toBe(true);
    snapshot = await result.json();
  }
  const internal = Object.values(snapshot.card_definitions).find(card => !card.user_creatable && card.label === "Skill"
    && snapshot.collection[card.id]?.unlocked && Object.values(snapshot.card_definitions).some(owner => owner.container?.member_type === card.id && snapshot.available_card_ids.includes(owner.id)))!;
  expect(internal).toBeTruthy();
  const owner = Object.values(snapshot.card_definitions).find(card => card.container?.member_type === internal.id)!;
  const packId = snapshot.collection[internal.id].source_pack_ids[0];
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  const library = page.getByRole("dialog", { name: "Pack & Card Library" });
  await library.getByRole("button", { name: /^Cards/ }).click();
  await expect(library.getByRole("checkbox", { name: /Show internal cards/ })).not.toBeChecked();
  expect(await library.locator(".library-source-group").count()).toBeGreaterThan(1);
  await expect(library.locator(".library-source-group[open]")).toHaveCount(0);
  await expect(library.locator(".library-internal-cards")).toHaveCount(0);
  await page.screenshot({ path: "../.tmp/library-grouped-packs.png" });
  await library.getByLabel("Source pack", { exact: true }).selectOption(`pack:${packId}`);
  await expect(library.locator(".library-source-group")).toHaveCount(1);
  await expect(library.getByRole("heading", { name: snapshot.packs[packId].definition.name, exact: true })).toBeVisible();
  const group = library.locator(".library-source-group");
  await group.locator(":scope > summary").click();
  await expect(group).not.toHaveAttribute("open");
  await library.getByLabel("Search cards", { exact: true }).fill(owner.label);
  await expect(group).toHaveAttribute("open", "");
  await library.getByRole("checkbox", { name: /Show internal cards/ }).check();
  await library.getByLabel("Search cards", { exact: true }).fill(`${owner.label} · Skill`);
  await library.getByRole("button", { name: `Inspect ${owner.label} · Skill`, exact: true }).click();
  const detail = library.getByRole("complementary", { name: "Card details" });
  await expect(detail).toContainText(internal.description);
  await expect(detail).toContainText(`Open ${owner.label} to use this card`);
  await expect(library.getByRole("button", { name: `Add ${owner.label} · Skill to deck`, exact: true })).toHaveCount(0);
  await page.screenshot({ path: "../.tmp/library-internal-skill.png" });
  await detail.getByRole("button", { name: `Inspect ${owner.label}`, exact: true }).click();
  await expect(detail.getByRole("heading", { name: owner.label, exact: true })).toBeVisible();
  await detail.getByRole("button", { name: "Add inspected card to deck" }).click();
  await expect(detail.getByRole("button", { name: "Remove inspected card from deck" })).toBeEnabled();
  await page.setViewportSize({ width: 640, height: 780 });
  await library.locator(".library-body").evaluate(element => { element.scrollTop = 0; });
  await page.screenshot({ path: "../.tmp/library-grouped-narrow.png" });
  expect(await library.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  expect(await library.locator(".library-body").evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});
