import { expect, test, type Page } from '@playwright/test';
import type { FaceDesign } from '../src/factory/types';
const surface = async (page: Page) => (JSON.parse(await page.getByTestId('studio-recipe').textContent() ?? '{}') as FaceDesign).studio!.modes.preview!;
const add = async (page: Page, name: string) => { await page.locator('.process-add-menu > summary').click(); await page.getByRole('button', { name, exact: true }).click(); };
const panel = async (page: Page, name: string) => page.locator('.process-element-panel > summary').filter({ hasText: name }).click();
const select = async (page: Page, name: string) => page.getByRole('navigation', { name: '设计步骤' }).getByRole('button', { name, exact: true }).click();

test('top path and local panels support independent copies, deletion and undo', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1050 }); await page.goto('/?card-studio');
  await select(page, '选择油墨第 1 层');
  await expect(page.locator('.face-sidebar .process-layer-list')).toHaveCount(0);
  await panel(page, '文本');
  await expect(page.getByRole('button', { name: '标题', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: '标题', exact: true })).toHaveAttribute('data-added', 'true');
  await add(page, '添加覆膜'); await page.getByLabel('覆膜类型', { exact: true }).selectOption('holo');
  await add(page, '添加烫金');
  for (const name of ['覆盖范围', '油墨类型', '移入此油墨层', '油墨层叠印方式']) await expect(page.getByLabel(name, { exact: true })).toHaveCount(0);
  await panel(page, '文本'); await page.getByRole('button', { name: '标题', exact: true }).click();
  const before = await surface(page), title = before.elements.at(-1)!;
  expect(title.kind).toBe('title'); expect(title.id).not.toBe('title');
  expect(before.design!.production!.layers!.at(-1)!.content!.elementIds).toEqual([title.id]);
  await page.getByRole('button', { name: '复制当前工艺层', exact: true }).click();
  const copy = (await surface(page)).elements.at(-1)!;
  expect(copy.id).not.toBe(title.id);
  await page.getByRole('button', { name: '编辑标题', exact: true }).click();
  const x = page.getByRole('spinbutton', { name: '位置 X', exact: true }); await x.fill('37'); await x.blur();
  expect((await surface(page)).elements.find(item => item.id === title.id)!.x).toBe(title.x);
  await page.getByRole('button', { name: '删除当前工艺层', exact: true }).click();
  expect((await surface(page)).elements.some(item => item.id === copy.id)).toBe(false);
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  expect((await surface(page)).elements.some(item => item.id === copy.id)).toBe(true);
  await select(page, '选择油墨第 1 层');
  await page.screenshot({ path: info.outputPath('layer-designer-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: info.outputPath('layer-designer-mobile.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('empty treatments coat the card while opaque passes start empty and follow their elements', async ({ page }) => {
  await page.goto('/?card-studio');
  const stage = page.locator('.face-stage-size .factory-artwork');
  await add(page, '添加覆膜');
  const filmId = (await surface(page)).design!.production!.layers!.at(-1)!.id;
  const film = stage.locator(`[data-process-layer="${filmId}"]`);
  await expect(film).toHaveAttribute('data-process-mask', 'all');
  await panel(page, '图形'); await page.getByRole('button', { name: '圆形', exact: true }).click();
  await expect(film).toHaveAttribute('data-process-mask', 'elements');
  await page.getByRole('button', { name: '删除此内容', exact: true }).click();
  await expect(film).toHaveAttribute('data-process-mask', 'all');
  await add(page, '添加烫金');
  const foilId = (await surface(page)).design!.production!.layers!.at(-1)!.id;
  const foil = stage.locator(`[data-process-layer="${foilId}"]`);
  await expect(foil).toHaveAttribute('data-process-mask', 'elements');
  await expect(foil).toHaveAttribute('data-material-ready', '');
  const alpha = () => foil.locator('canvas').evaluate(node => { const c = node as HTMLCanvasElement; return c.getContext('2d')!.getImageData(Math.floor(c.width / 2), Math.floor(c.height / 2), 1, 1).data[3]; });
  await expect.poll(alpha).toBe(0);
  await panel(page, '图形'); await page.getByRole('button', { name: '铺满卡面', exact: true }).click();
  await expect.poll(alpha).toBeGreaterThan(0);
  const full = (await surface(page)).shapes.at(-1)!;
  expect(full.width).toBe((await surface(page)).width); expect(full.height).toBe((await surface(page)).height);
  await page.getByRole('button', { name: '删除当前工艺层', exact: true }).click();
  expect((await surface(page)).shapes.some(shape => shape.id === full.id)).toBe(false);
  await select(page, '卡纸'); await expect(stage.locator('[data-process-layer]')).toHaveCount(0);
});

test('patterns and image uploads stay in their ink layer; layouts and combinations share presets', async ({ page }, info) => {
  await page.goto('/?card-studio'); await select(page, '选择油墨第 1 层');
  await expect(page.getByText('版式与底纹', { exact: true })).toHaveCount(0);
  await panel(page, '图像'); await page.getByRole('button', { name: '几何网格', exact: true }).click();
  await add(page, '添加油墨'); await panel(page, '图像'); await page.getByRole('button', { name: '放射线', exact: true }).click();
  const png = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = 48; c.height = 64; const ctx = c.getContext('2d')!; ctx.fillStyle = '#698676'; ctx.fillRect(0, 0, 24, 64); return c.toDataURL(); });
  await page.getByLabel('上传图像元素', { exact: true }).setInputFiles({ name: 'art.png', mimeType: 'image/png', buffer: Buffer.from(png.split(',')[1], 'base64') });
  await expect.poll(async () => (await surface(page)).elements.filter(item => item.image_png === png).length).toBe(1);
  const value = await surface(page), image = value.elements.at(-1)!, layers = value.design!.production!.layers!;
  expect(layers.map(layer => layer.pattern!.motif)).toEqual(['grid', 'rays']);
  expect(layers[1].content!.elementIds).toEqual([image.id]);
  await expect(page.locator(`.face-stage-size [data-process-layer="${layers[1].id}"] [data-face-element="${image.id}"] img`)).toHaveAttribute('src', png);
  await page.getByRole('button', { name: '预设', exact: true }).click();
  await expect(page.getByRole('button', { name: '应用 Hero 版式', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '添加哑膜金字', exact: true }).scrollIntoViewIfNeeded();
  await expect(page.getByRole('button', { name: '添加哑膜金字', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '添加哑膜金字', exact: true }).click();
  expect((await surface(page)).design!.production!.layers!.map(layer => layer.kind)).toEqual(['ink', 'ink', 'laminate', 'foil', 'uv']);
  await page.screenshot({ path: info.outputPath('layer-designer-patterns.png'), fullPage: true });
});
