import { expect, test } from "@playwright/test";

test("packs, collection and active decks persist and recover from plugin disable", async ({ page, request, context }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  const controls = page.getByRole("complementary", { name: "World status and controls" });
  await expect(controls.locator(".top-actions button")).toHaveCount(4);
  expect(await controls.evaluate(panel => {
    const box = panel.getBoundingClientRect();
    return [...panel.querySelectorAll("button")].every(button => { const rect = button.getBoundingClientRect(); return rect.left >= box.left && rect.right <= box.right && rect.top >= box.top && rect.bottom <= box.bottom; });
  })).toBe(true);
  const tray = page.getByRole("complementary", { name: "Active card deck" });
  await tray.hover();
  await expect(tray.getByText("Build your deck")).toBeVisible();
  await expect(tray.getByRole("button", { name: /^Place / })).toHaveCount(0);
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  const library = page.getByRole("dialog", { name: "Pack & Card Library" });
  const pack = library.locator("article").filter({ has: page.getByRole("heading", { name: "Core essentials", exact: true }) });
  await expect(pack.getByText("Unopened", { exact: true })).toBeVisible();
  await pack.getByText("Preview contents", { exact: false }).click();
  await expect(pack.getByText("Text file", { exact: true })).toBeVisible();
  await pack.getByRole("button", { name: "Open Pack", exact: true }).click();
  await expect(library.getByRole("status")).toContainText("Core essentials opened");
  await library.getByRole("button", { name: "Browse cards", exact: true }).click();
  await library.getByLabel("Search cards", { exact: true }).fill("Text file");
  await library.getByRole("button", { name: "Inspect Text file" }).click();
  await expect(library.getByRole("complementary", { name: "Card details" })).toContainText("Core essentials");
  await library.getByRole("button", { name: "Add Text file to deck" }).click();
  await expect(library.getByRole("button", { name: "Remove Text file from deck" })).toBeVisible();
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Place Text file", exact: true })).toBeVisible();
  await expect(tray.getByRole("button", { name: "Place Agent", exact: true })).toHaveCount(0);
  await tray.getByRole("button", { name: "Place Text file", exact: true }).dragTo(page.locator(".react-flow__pane").first(), { targetPosition: { x: 420, y: 250 } });
  await expect.poll(async () => (await (await request.get("/api/nodes")).json()).some((node: { type: string }) => node.type === "text")).toBe(true);
  await page.keyboard.press("Control+z");
  await expect.poll(async () => (await (await request.get("/api/nodes")).json()).length).toBe(0);
  await page.keyboard.press("Control+Shift+z");
  await expect.poll(async () => (await (await request.get("/api/nodes")).json()).length).toBe(1);
  await page.reload();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Place Text file", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  await library.getByRole("button", { name: /^Cards/ }).click();
  await library.getByRole("button", { name: "Remove Text file from deck" }).click();
  await expect(library.getByRole("button", { name: "Add Text file to deck" })).toBeVisible();
  await library.getByRole("button", { name: /^Decks/ }).click();
  await library.getByLabel("New deck name").fill("Research kit");
  await library.getByRole("button", { name: "Create deck", exact: true }).click();
  await expect(library.getByRole("heading", { name: "Research kit", exact: true })).toBeVisible();
  await expect(library.getByRole("button", { name: "Active deck", exact: true })).toBeDisabled();
  await library.getByRole("button", { name: /^Packs/ }).click();
  const taskPack = library.locator("article").filter({ has: page.getByRole("heading", { name: "Task Board", exact: true }) });
  await taskPack.getByRole("button", { name: "Open Pack", exact: true }).click();
  await library.getByRole("button", { name: "Browse cards", exact: true }).click();
  await library.getByLabel("Search cards", { exact: true }).fill("Task Board");
  await library.getByRole("button", { name: "Add Task Board to deck" }).click();
  await library.getByRole("button", { name: /^Packs/ }).click();
  await library.getByLabel("Search packs").fill("Task Board");
  await taskPack.getByRole("button", { name: "Disable plugin" }).click();
  await expect(taskPack.getByText("Plugin disabled", { exact: true })).toBeVisible();
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Task Board unavailable" })).toBeDisabled();
  await expect(tray.getByRole("button", { name: "Place Text file", exact: true })).toHaveCount(0);
  await page.reload();
  await tray.hover();
  await expect(tray.getByRole("tab", { name: /Research kit/ })).toHaveAttribute("aria-selected", "true");
  await expect(tray.getByRole("button", { name: "Task Board unavailable" })).toBeDisabled();
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  await taskPack.getByRole("button", { name: "Enable plugin" }).click();
  await expect(taskPack.getByText("Installed · Enabled", { exact: true })).toBeVisible();
  await library.getByRole("button", { name: /^Store/ }).click();
  await expect(library.getByText("Coming later", { exact: true })).toBeVisible();
  await page.screenshot({ path: "../.tmp/library-store.png" });
  await library.getByRole("button", { name: /^Packs/ }).click();
  await page.screenshot({ path: "../.tmp/library-packs.png" });
  await library.getByRole("button", { name: /^Cards/ }).click();
  await page.screenshot({ path: "../.tmp/library-cards.png" });
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.hover();
  await expect(tray.getByRole("button", { name: "Place Task Board", exact: true })).toBeEnabled();
  // A second window receives an authoritative deck change over the event stream.
  const other = await context.newPage();
  await other.goto("/");
  await other.getByRole("complementary", { name: "Active card deck" }).hover();
  await expect(other.getByRole("button", { name: "Place Task Board", exact: true })).toBeEnabled();
  const state = await (await request.get("/api/card-library")).json();
  const response = await request.post("/api/card-library/actions", { data: { action: "update_deck", id: state.active_deck_id, entries: [], expected_revision: state.revision } });
  expect(response.ok()).toBe(true);
  await expect(other.getByRole("button", { name: "Place Task Board", exact: true })).toHaveCount(0);
  await expect(tray.getByRole("button", { name: "Place Task Board", exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 640, height: 780 });
  await page.getByRole("button", { name: "Open Pack and Card Library" }).click();
  await page.screenshot({ path: "../.tmp/library-narrow.png" });
  expect(await library.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await library.getByRole("button", { name: "Close Library" }).click();
  await tray.getByRole("button", { name: "Create a new card deck" }).click();
  await tray.getByLabel("Deck name", { exact: true }).fill("Quick tools");
  await tray.getByLabel("Deck icon", { exact: true }).selectOption("zap");
  await page.screenshot({ path: "../.tmp/deck-create-controls.png" });
  await tray.getByRole("button", { name: "Create deck", exact: true }).click();
  await expect(tray.getByRole("tab", { name: /Quick tools/ }).locator("svg")).toHaveClass(/lucide-zap/);
  await page.reload();
  await expect(tray.getByRole("tab", { name: /Quick tools/ }).locator("svg")).toHaveClass(/lucide-zap/);
  await expect(tray.getByRole("tab", { name: /Research kit/ }).locator("svg")).toHaveClass(/lucide-folder/);
  expect(await controls.evaluate(panel => {
    const box = panel.getBoundingClientRect();
    return [...panel.querySelectorAll("button")].every(button => { const rect = button.getBoundingClientRect(); return rect.left >= box.left && rect.right <= box.right && rect.top >= box.top && rect.bottom <= box.bottom; });
  })).toBe(true);
  await page.screenshot({ path: "../.tmp/deck-controls-fixed.png" });
  expect(errors).toEqual([]);
});
