import { expect, test } from '@playwright/test';
import { mkdir, mkdtemp, rmdir, writeFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { resetTutorialProfile } from './tutorial-profile';

for (const kind of ['folder', 'file'] as const) test(`global and Sandbox ${kind} variables share editing, permissions and persistence`, async ({ page, request }, testInfo) => {
  test.setTimeout(60_000);
  const scratch = path.resolve(process.cwd(), '../.tmp');
  await mkdir(scratch, { recursive: true });
  const folder = await mkdtemp(path.join(scratch, 'folder-ui-'));
  const source = kind === 'file' ? path.join(folder, 'model.pt') : folder;
  if (kind === 'file') await writeFile(source, 'model fixture');
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await resetTutorialProfile(request);
  let nodeId: string | undefined;
  try {
    await page.goto('/');
    await page.getByRole('button', { name: 'Start blank', exact: true }).click();
    await page.getByRole('button', { name: 'Open settings', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'Settings', exact: true });
    await settings.getByRole('button', { name: 'Sandbox', exact: true }).click();
    await settings.getByRole('button', { name: 'Add variable', exact: true }).click();
    await settings.getByLabel('Environment variable 1 name', { exact: true }).fill('MODELS');
    await settings.getByLabel('Environment variable 1 type').selectOption("path");
    await expect(settings.getByLabel('Environment variable 1 access')).toHaveValue('read_only');
    await page.route(`**/api/desktop/pick-${kind}`, route => route.fulfill({ json: { path: source } }));
    await settings.getByLabel("Browse for Environment variable 1 path").click();
    await settings.getByRole("button", { name: kind === "file" ? "Choose file" : "Choose folder", exact: true }).click();
    await expect(settings.getByLabel("Environment variable 1 path", { exact: true })).toHaveValue(source);
    await settings.getByRole('button', { name: 'Save settings', exact: true }).click();
    await expect(settings.getByText('Settings saved', { exact: true })).toBeVisible();
    const global = await (await request.get('/api/settings/sandbox')).json();
    const reference = global.environment_variables.MODELS.path_ref;
    expect(global.folder_bindings[reference]).toEqual({ path: source, access: 'read_only', kind });
    await page.screenshot({ path: testInfo.outputPath(`global-${kind}.png`) });
    await page.getByRole('button', { name: 'Close settings', exact: true }).click();
    const response = await request.post('/api/nodes', { data: { type: 'sandbox', name: 'Folder lab', position: { x: 550, y: 340 } } });
    expect(response.status()).toBe(201);
    nodeId = (await response.json()).id;
    await page.reload();
    const card = page.locator(`[data-card-id="${nodeId}"]`);
    await card.getByRole('tab', { name: 'Settings', exact: true }).click();
    await card.getByText('Environment variables', { exact: true }).click();
    await card.getByRole('button', { name: 'Add variable', exact: true }).click();
    await card.getByLabel('Environment variable 1 name', { exact: true }).fill('MODELS');
    await card.getByLabel('Environment variable 1 type').selectOption("path");
    await card.getByLabel("Environment variable 1 path", { exact: true }).fill(source);
    await card.getByLabel('Environment variable 1 access').selectOption('read_write');
    await card.getByRole('button', { name: 'Save environment', exact: true }).click();
    await expect(card.getByText('Applies to the next command.', { exact: true })).toBeVisible();
    const document = await (await request.get(`/api/nodes/${nodeId}/document`)).json();
    expect(JSON.stringify(document)).not.toContain(source);
    const local = await (await request.get(`/api/nodes/${nodeId}/environment-folders`)).json();
    expect(local[document.value.variables.MODELS.path_ref]).toEqual({ path: source, access: 'read_write', kind });
    await card.getByRole('button', { name: 'Reload environment', exact: true }).click();
    await expect(card.getByLabel("Environment variable 1 path", { exact: true })).toHaveValue(source);
    await expect(card.getByLabel('Environment variable 1 access')).toHaveValue('read_write');
    await page.screenshot({ path: testInfo.outputPath(`sandbox-${kind}.png`) });
    await card.getByLabel('Remove environment variable 1', { exact: true }).click();
    await card.getByRole('button', { name: 'Save environment', exact: true }).click();
    await expect.poll(async () => (await (await request.get(`/api/nodes/${nodeId}/document`)).json()).value.variables).toEqual({});
    expect(await (await request.get(`/api/nodes/${nodeId}/environment-folders`)).json()).toEqual({});
    expect(errors).toEqual([]);
  } finally {
    if (nodeId) await request.delete(`/api/nodes/${nodeId}`);
    await request.put('/api/settings/sandbox', { data: { environment_variables: {} } });
    if (kind === 'file') await unlink(source);
    await rmdir(folder);
  }
});
