import { expect, test } from '@playwright/test';
import type { LibrarySnapshot } from '../src/state/cardLibrary';

test('library adds directly to the visible bottom deck at desktop and narrow widths', async ({ page, request }) => {
  test.setTimeout(60000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const read = async (): Promise<LibrarySnapshot> => (await request.get('/api/card-library')).json();
  const initial = await read();
  const pack = Object.values(initial.packs).find(pack => pack.definition.cards.includes('text'))!;
  const opened = await request.post('/api/card-library/actions', { data: { action: 'open_pack', id: pack.definition.id, expected_revision: initial.revision } });
  expect(opened.ok()).toBe(true);
  await page.goto('/');
  await page.getByRole('button', { name: 'Open Pack and Card Library' }).click();
  const library = page.getByRole('dialog', { name: 'Pack & Card Library' });
  await expect(library.getByRole('button', { name: /^Decks/ })).toHaveCount(0);
  await library.getByRole('button', { name: /^Cards/ }).click();
  await library.getByLabel('Search cards', { exact: true }).fill('Text file');
  const deck = page.getByRole('complementary', { name: 'Active card deck' });
  await deck.getByRole('button', { name: 'Create a new card deck' }).click();
  await deck.getByLabel('Deck name', { exact: true }).fill('Library destination');
  await deck.getByRole('button', { name: 'Create deck', exact: true }).click();
  await expect(deck.getByRole('tab', { name: /Library destination/ })).toHaveAttribute('aria-selected', 'true');
  await expect(library.locator('.library-deck-rail')).toHaveCount(0);
  const drag = async (destination: import('@playwright/test').Locator) => {
    const source = library.locator('[data-library-card="text"]');
    await source.scrollIntoViewIfNeeded();
    const a = (await source.boundingBox())!, b = (await destination.boundingBox())!;
    await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2);
    await page.mouse.down();
    await page.mouse.move(b.x + b.width * .7, b.y + b.height / 2, { steps: 12 });
    await expect(page.locator('.palette-drag-preview')).toBeVisible();
    await page.mouse.up();
  };
  // Legions is an ordinary persistent destination, including while Library is open.
  const legionsTab = deck.locator('[role="tab"][data-deck-destination="saved-legions"]');
  await expect(legionsTab).toBeEnabled();
  await drag(legionsTab);
  await expect(legionsTab).toHaveAttribute('aria-selected', 'true');
  await expect(deck.locator('[data-palette-card="text"]')).toBeVisible();
  await library.getByRole('button', { name: 'Remove Text file from deck', exact: true }).click();
  await expect(deck.locator('[data-palette-card="text"]')).toHaveCount(0);
  expect((await read()).decks.find(item => item.id === 'saved-legions')!.entries).toEqual([]);
  await deck.getByRole('tab', { name: /Library destination/ }).click();
  for (const width of [1280, 720, 390]) {
    await page.setViewportSize({ width, height: 800 });
    await expect(deck.locator('.deck-stage')).toBeVisible();
    await expect.poll(async () => {
      const a = (await library.boundingBox())!, b = (await deck.boundingBox())!;
      return a.y + a.height <= b.y;
    }).toBe(true);
    await drag(deck.locator('.deck-stage'));
    await expect(deck.locator('[data-palette-card="text"]')).toBeVisible();
    await expect(library.getByRole('button', { name: 'Remove Text file from deck', exact: true })).toBeVisible();
    expect((await read()).decks.find(item => item.name === 'Library destination')!.entries).toEqual([{ kind: 'node', id: 'text' }]);
    await page.screenshot({ path: `test-results/library-bottom-deck-${width}.png` });
  }
  await page.setViewportSize({ width: 1280, height: 800 });
  await drag(deck.locator('[data-deck-destination]').first());
  await expect(deck.locator('[data-palette-card="text"]')).toBeVisible();
  expect((await read()).decks.find(item => item.name === 'Library destination')!.entries).toHaveLength(1);
  await deck.getByRole('tab', { name: /Library destination/ }).click();
  await deck.getByRole('button', { name: 'Edit deck', exact: true }).click();
  await deck.getByLabel('Deck name', { exact: true }).fill('Renamed destination');
  await deck.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(deck.getByRole('tab', { name: /Renamed destination/ })).toHaveAttribute('aria-selected', 'true');
  expect((await read()).decks.find(item => item.name === 'Renamed destination')!.entries).toHaveLength(1);
  await page.setViewportSize({ width: 390, height: 800 });
  await deck.getByRole('button', { name: 'Edit deck', exact: true }).click();
  await expect(deck.getByRole('button', { name: 'Delete deck', exact: true })).toBeInViewport();
  await expect.poll(async () => { const box = (await deck.boundingBox())!; return box.x >= 0 && box.x + box.width <= 390; }).toBe(true);
  await page.screenshot({ path: 'test-results/library-edit-deck-390.png' });
  await deck.getByRole('button', { name: 'Delete deck', exact: true }).click();
  await expect(deck.getByRole('tab', { name: /Renamed destination/ })).toHaveCount(0);
  expect((await read()).collection.text.unlocked).toBe(true);
  // The default Legions deck can be deleted, and must not be recreated by refresh.
  await legionsTab.click();
  await deck.getByRole('button', { name: 'Edit deck', exact: true }).click();
  await deck.getByRole('button', { name: 'Delete deck', exact: true }).click();
  await expect(legionsTab).toHaveCount(0);
  expect((await read()).decks.map(item => item.id)).toEqual(['starter']);
  await deck.getByRole('button', { name: 'Edit deck', exact: true }).click();
  await expect(deck.getByRole('button', { name: 'Delete deck', exact: true })).toBeDisabled();
  await deck.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.setViewportSize({ width: 1280, height: 800 });
  const trash = deck.getByRole('region', { name: 'Discard card' });
  const card = deck.locator('[data-palette-card="text"]');
  const startDiscard = async () => {
    const box = (await card.boundingBox())!;
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
  };
  await startDiscard();
  const bin = (await trash.boundingBox())!;
  await page.mouse.move(bin.x + bin.width + 50, bin.y + bin.height / 2, { steps: 12 });
  const preview = page.locator('.palette-drag-preview');
  await expect(preview).toHaveAttribute('data-discard-progress', '0.500');
  await expect(trash).toHaveAttribute('data-discard-near', '');
  await page.screenshot({ path: 'test-results/deck-shred-approach.png' });
  await page.mouse.move(bin.x + bin.width / 2, bin.y + bin.height / 2, { steps: 12 });
  await expect(preview).toHaveAttribute('data-discard-progress', '1.000');
  expect((await read()).decks[0].entries).toHaveLength(1); // Preview alone does not delete.
  await page.screenshot({ path: 'test-results/deck-shred-over-bin.png' });
  await page.mouse.move(bin.x + 250, bin.y, { steps: 12 });
  await expect(preview).toHaveAttribute('data-discard-progress', '0.000');
  await expect(preview.locator('.palette-shred-piece:visible')).toHaveCount(0);
  await page.keyboard.press('Escape');
  await page.mouse.up();
  await expect(preview).toHaveCount(0);
  await expect(trash).not.toHaveAttribute('data-discard-near');
  expect((await read()).decks[0].entries).toHaveLength(1);
  await startDiscard();
  await page.mouse.move(bin.x + bin.width / 2, bin.y + bin.height / 2, { steps: 12 });
  await page.mouse.up();
  await expect(card).toHaveCount(0);
  expect((await read()).collection.text.unlocked).toBe(true);
  await library.getByRole('button', { name: 'Close Library' }).click();
  await expect(library).not.toBeVisible();
  await page.getByRole('button', { name: 'Open Pack and Card Library' }).click();
  await page.keyboard.press('Escape');
  await expect(library).not.toBeVisible();
  expect(errors).toEqual([]);
});
