import { expect, test } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

test("build a toolbox, import a skill, export a plugin and restore the local copy", async ({ page, request }, testInfo) => {
  await page.setViewportSize({ width: 1600, height: 1100 });
  const created = await request.post("/api/nodes", { data: { type: "oaw.skills", name: "Review toolbox", position: { x: 710, y: 430 } } });
  expect(created.status()).toBe(201);
  const node = await created.json();
  const url = `/api/nodes/${node.id}`;
  try {
    await page.goto("/");
    let card = page.locator(`[data-card-id="${node.id}"]`);
    await card.locator(".card-kind-icon").click();
    await card.getByRole("button", { name: "Open workspace", exact: true }).click();
    const box = page.getByRole("dialog", { name: "Review toolbox workspace", exact: true });
    await box.getByRole("button", { name: "Toolbox settings", exact: true }).click();
    await box.getByLabel("Toolbox name", { exact: true }).fill("Review Bench");
    await box.getByLabel("Shared instructions").fill("Read the diff, check the behavior, then report the outcome.");
    await box.getByLabel("Author", { exact: true }).fill("Example");
    await box.getByLabel("Package ID").fill("example.review");
    await box.getByRole("button", { name: "Save toolbox", exact: true }).click();
    await box.getByRole("button", { name: "Add skill", exact: true }).click();
    await box.getByLabel("Skill name").fill("Review a patch");
    await box.getByLabel("When to use").fill("Before handing over a code change.");
    await box.getByLabel("Import SKILL.md").setInputFiles({ name: "SKILL.md", mimeType: "text/markdown", buffer: Buffer.from("# Review\nTrace the changed behavior and inspect the result.") });
    await expect(box.getByRole("textbox", { name: "Instructions", exact: true })).toHaveValue(/Trace the changed behavior/);
    await box.getByRole("button", { name: "Default settings", exact: true }).click();
    const defaults = box.locator(".skill-defaults-editor").first();
    await defaults.getByRole("button", { name: "Add setting", exact: true }).click();
    await box.getByLabel("Setting 1 name", { exact: true }).fill("language");
    await box.getByLabel("Setting 1 value", { exact: true }).fill("English");
    await defaults.getByRole("button", { name: "Add setting", exact: true }).click();
    await box.getByLabel("Setting 2 name", { exact: true }).fill("checks");
    await box.getByLabel("Setting 2 type", { exact: true }).selectOption("group");
    const group = defaults.locator(".skill-defaults-editor");
    await group.getByRole("button", { name: "Add setting", exact: true }).click();
    await box.getByLabel("Setting 2 1 name", { exact: true }).fill("limit");
    await box.getByLabel("Setting 2 1 type", { exact: true }).selectOption("number");
    await box.getByLabel("Setting 2 1 value", { exact: true }).fill("3");
    await group.getByRole("button", { name: "Add setting", exact: true }).click();
    await box.getByLabel("Setting 2 2 name", { exact: true }).fill("enabled");
    await box.getByLabel("Setting 2 2 type", { exact: true }).selectOption("boolean");
    await box.getByLabel("Setting 2 2 value", { exact: true }).check();
    await defaults.getByRole("button", { name: "Add setting", exact: true }).last().click();
    await box.getByLabel("Setting 3 name", { exact: true }).fill("formats");
    await box.getByLabel("Setting 3 type", { exact: true }).selectOption("list");
    await box.getByRole("button", { name: "Add item", exact: true }).click();
    await box.getByLabel("Setting 3 1 value", { exact: true }).fill("md");
    await box.getByRole("button", { name: "Files and folders", exact: true }).click();
    await box.getByLabel("New file or folder name").fill("scripts");
    await box.getByRole("button", { name: "Create folder", exact: true }).click();
    await box.getByLabel("New file or folder name").fill("check.py");
    await box.getByRole("button", { name: "Create text file", exact: true }).click();
    await box.getByRole("textbox", { name: "File contents", exact: true }).fill("print('review')\n");
    await box.getByLabel("Current folder").selectOption("");
    const folder = testInfo.outputPath("skill-folder");
    await mkdir(path.join(folder, "references"), { recursive: true });
    await mkdir(path.join(folder, "custom/templates"), { recursive: true });
    await writeFile(path.join(folder, "references/checklist.md"), "Check the public API.");
    await writeFile(path.join(folder, "custom/templates/report.md"), "# Findings");
    await box.getByLabel("Import skill folder").setInputFiles(folder);
    await expect(box.getByLabel("Current folder")).toHaveValue(/references|custom/);
    await box.getByLabel("Current folder").selectOption("");
    await box.getByLabel("New file or folder name").fill("assets");
    await box.getByRole("button", { name: "Create folder", exact: true }).click();
    const logo = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l8AAAAASUVORK5CYII=";
    await box.getByLabel("Import skill files").setInputFiles({ name: "logo.png", mimeType: "image/png", buffer: Buffer.from(logo, "base64") });
    await expect(box.getByRole("img", { name: "logo.png" })).toBeVisible();
    await box.getByLabel("File path", { exact: true }).fill("assets/brand/logo.png");
    await box.getByRole("button", { name: "Move / rename", exact: true }).click();
    await page.screenshot({ path: "../.open-agent-world/skill-toolbox-files.png" });
    await box.getByRole("button", { name: "Save skill", exact: true }).click();
    await expect(box.getByRole("button", { name: "Edit skill Review a patch", exact: true })).toBeEnabled();
    await page.screenshot({ path: "../.open-agent-world/skill-toolbox-light.png" });
    const downloadPromise = page.waitForEvent("download");
    await box.getByRole("link", { name: "Export plugin" }).click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toBe("oaw-toolbox-example-review-0.1.0.zip");
    await download.saveAs("../.open-agent-world/skill-toolbox-export.zip");
    await page.getByRole("button", { name: "Use dark theme" }).click();
    await page.screenshot({ path: "../.open-agent-world/skill-toolbox-dark.png" });
    await page.getByRole("button", { name: "Use light theme" }).click();
    await page.reload();
    await expect(box.getByRole("button", { name: "Edit skill Review a patch", exact: true })).toBeVisible();
    await box.getByRole("button", { name: "Edit skill Review a patch", exact: true }).click();
    await box.getByRole("button", { name: "Default settings", exact: true }).click();
    await expect(box.getByRole("group", { name: "limit", exact: true }).getByRole("spinbutton")).toHaveValue("3");
    await expect(box.getByRole("group", { name: "enabled", exact: true }).getByRole("checkbox")).toBeChecked();
    await expect(box.getByRole("group", { name: "formats", exact: true }).getByPlaceholder("Value", { exact: true })).toHaveValue("md");
    await box.getByRole("group", { name: "language", exact: true }).getByPlaceholder("Value", { exact: true }).fill("Chinese");
    await page.screenshot({ path: "../.open-agent-world/skill-toolbox-settings.png" });
    await box.getByRole("button", { name: "Save skill", exact: true }).click();
    await expect(box.getByRole("button", { name: "Edit skill Review a patch", exact: true })).toBeEnabled();
    await box.getByRole("button", { name: "Close workspace", exact: true }).click();
    card = page.locator(`[data-card-id="${node.id}"]`);
    await card.locator(".card-kind-icon").click();
    await card.getByRole("button", { name: "Remove Review toolbox", exact: true }).click();
    await expect(card).toHaveCount(0);
    await page.getByRole("button", { name: "Undo last canvas action", exact: true }).click();
    await expect(card).toHaveCount(1);
    const restored = await (await request.get(url + "/document")).json();
    expect(restored.value.skills[0].files["references/checklist.md"]).toBe("Check the public API.");
    expect(restored.value.skills[0].files["scripts/check.py"]).toBe("print('review')\n");
    expect(restored.value.skills[0].files["custom/templates/report.md"]).toBe("# Findings");
    expect(restored.value.skills[0].files["assets/brand/logo.png"].data_base64).toBe(logo);
    expect(restored.value.skills[0].defaults).toEqual({ language: "Chinese", checks: { limit: 3, enabled: true }, formats: ["md"] });
    expect(restored.value.instructions).toContain("Read the diff");
  } finally { await request.delete(url); }
});
